// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/appliance.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplianceArtifactKind int32

const (
	ApplianceArtifactKind_APPLIANCE_ARTIFACT_KIND_UNSPECIFIED ApplianceArtifactKind = 0
	ApplianceArtifactKind_APPLIANCE_ARTIFACT_SUPPORT_BUNDLE   ApplianceArtifactKind = 1 // redacted diagnostics
	ApplianceArtifactKind_APPLIANCE_ARTIFACT_CONFIG_ARCHIVE   ApplianceArtifactKind = 2 // configuration, without proxy binaries; holds the control-plane token
)

// Enum value maps for ApplianceArtifactKind.
var (
	ApplianceArtifactKind_name = map[int32]string{
		0: "APPLIANCE_ARTIFACT_KIND_UNSPECIFIED",
		1: "APPLIANCE_ARTIFACT_SUPPORT_BUNDLE",
		2: "APPLIANCE_ARTIFACT_CONFIG_ARCHIVE",
	}
	ApplianceArtifactKind_value = map[string]int32{
		"APPLIANCE_ARTIFACT_KIND_UNSPECIFIED": 0,
		"APPLIANCE_ARTIFACT_SUPPORT_BUNDLE":   1,
		"APPLIANCE_ARTIFACT_CONFIG_ARCHIVE":   2,
	}
)

func (x ApplianceArtifactKind) Enum() *ApplianceArtifactKind {
	p := new(ApplianceArtifactKind)
	*p = x
	return p
}

func (x ApplianceArtifactKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplianceArtifactKind) Descriptor() protoreflect.EnumDescriptor {
	return file_client_appliance_proto_enumTypes[0].Descriptor()
}

func (ApplianceArtifactKind) Type() protoreflect.EnumType {
	return &file_client_appliance_proto_enumTypes[0]
}

func (x ApplianceArtifactKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplianceArtifactKind.Descriptor instead.
func (ApplianceArtifactKind) EnumDescriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{0}
}

type ApplianceArtifactState int32

const (
	ApplianceArtifactState_APPLIANCE_ARTIFACT_STATE_UNSPECIFIED ApplianceArtifactState = 0
	ApplianceArtifactState_APPLIANCE_ARTIFACT_RUNNING           ApplianceArtifactState = 1
	ApplianceArtifactState_APPLIANCE_ARTIFACT_READY             ApplianceArtifactState = 2
	ApplianceArtifactState_APPLIANCE_ARTIFACT_FAILED            ApplianceArtifactState = 3
	ApplianceArtifactState_APPLIANCE_ARTIFACT_EXPIRED           ApplianceArtifactState = 4
)

// Enum value maps for ApplianceArtifactState.
var (
	ApplianceArtifactState_name = map[int32]string{
		0: "APPLIANCE_ARTIFACT_STATE_UNSPECIFIED",
		1: "APPLIANCE_ARTIFACT_RUNNING",
		2: "APPLIANCE_ARTIFACT_READY",
		3: "APPLIANCE_ARTIFACT_FAILED",
		4: "APPLIANCE_ARTIFACT_EXPIRED",
	}
	ApplianceArtifactState_value = map[string]int32{
		"APPLIANCE_ARTIFACT_STATE_UNSPECIFIED": 0,
		"APPLIANCE_ARTIFACT_RUNNING":           1,
		"APPLIANCE_ARTIFACT_READY":             2,
		"APPLIANCE_ARTIFACT_FAILED":            3,
		"APPLIANCE_ARTIFACT_EXPIRED":           4,
	}
)

func (x ApplianceArtifactState) Enum() *ApplianceArtifactState {
	p := new(ApplianceArtifactState)
	*p = x
	return p
}

func (x ApplianceArtifactState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplianceArtifactState) Descriptor() protoreflect.EnumDescriptor {
	return file_client_appliance_proto_enumTypes[1].Descriptor()
}

func (ApplianceArtifactState) Type() protoreflect.EnumType {
	return &file_client_appliance_proto_enumTypes[1]
}

func (x ApplianceArtifactState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplianceArtifactState.Descriptor instead.
func (ApplianceArtifactState) EnumDescriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{1}
}

// One `show health` line.
type ApplianceHealthItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Area          string                 `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`         // agent, listener, nic, firewall, upgrade, …
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // ok | info | WARN | CRIT (as the console prints it)
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`      // 0 ok, 1 info, 2 warn, 3 crit
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplianceHealthItem) Reset() {
	*x = ApplianceHealthItem{}
	mi := &file_client_appliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceHealthItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceHealthItem) ProtoMessage() {}

func (x *ApplianceHealthItem) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceHealthItem.ProtoReflect.Descriptor instead.
func (*ApplianceHealthItem) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{0}
}

func (x *ApplianceHealthItem) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ApplianceHealthItem) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ApplianceHealthItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ApplianceHealthItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ApplianceHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CheckedAt      string                 `protobuf:"bytes,1,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"` // RFC 3339
	Worst          string                 `protobuf:"bytes,2,opt,name=worst,proto3" json:"worst,omitempty"`
	WorstLevel     int32                  `protobuf:"varint,3,opt,name=worst_level,json=worstLevel,proto3" json:"worst_level,omitempty"`
	Items          []*ApplianceHealthItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`     // worst first
	Missing        []string               `protobuf:"bytes,5,rep,name=missing,proto3" json:"missing,omitempty"` // probes that did not answer in time
	ElapsedSeconds float64                `protobuf:"fixed64,6,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplianceHealth) Reset() {
	*x = ApplianceHealth{}
	mi := &file_client_appliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceHealth) ProtoMessage() {}

func (x *ApplianceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceHealth.ProtoReflect.Descriptor instead.
func (*ApplianceHealth) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{1}
}

func (x *ApplianceHealth) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

func (x *ApplianceHealth) GetWorst() string {
	if x != nil {
		return x.Worst
	}
	return ""
}

func (x *ApplianceHealth) GetWorstLevel() int32 {
	if x != nil {
		return x.WorstLevel
	}
	return 0
}

func (x *ApplianceHealth) GetItems() []*ApplianceHealthItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ApplianceHealth) GetMissing() []string {
	if x != nil {
		return x.Missing
	}
	return nil
}

func (x *ApplianceHealth) GetElapsedSeconds() float64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

type ApplianceBootSlots struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       string                 `protobuf:"bytes,1,opt,name=running,proto3" json:"running,omitempty"` // a | b
	Committed     string                 `protobuf:"bytes,2,opt,name=committed,proto3" json:"committed,omitempty"`
	NextBoot      string                 `protobuf:"bytes,3,opt,name=next_boot,json=nextBoot,proto3" json:"next_boot,omitempty"` // "-" when the next boot is the committed slot
	SlotA         string                 `protobuf:"bytes,4,opt,name=slot_a,json=slotA,proto3" json:"slot_a,omitempty"`          // "installed (0.5.0)", "empty", …
	SlotB         string                 `protobuf:"bytes,5,opt,name=slot_b,json=slotB,proto3" json:"slot_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplianceBootSlots) Reset() {
	*x = ApplianceBootSlots{}
	mi := &file_client_appliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceBootSlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceBootSlots) ProtoMessage() {}

func (x *ApplianceBootSlots) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceBootSlots.ProtoReflect.Descriptor instead.
func (*ApplianceBootSlots) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{2}
}

func (x *ApplianceBootSlots) GetRunning() string {
	if x != nil {
		return x.Running
	}
	return ""
}

func (x *ApplianceBootSlots) GetCommitted() string {
	if x != nil {
		return x.Committed
	}
	return ""
}

func (x *ApplianceBootSlots) GetNextBoot() string {
	if x != nil {
		return x.NextBoot
	}
	return ""
}

func (x *ApplianceBootSlots) GetSlotA() string {
	if x != nil {
		return x.SlotA
	}
	return ""
}

func (x *ApplianceBootSlots) GetSlotB() string {
	if x != nil {
		return x.SlotB
	}
	return ""
}

type ApplianceUpgrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`         // the upgrader's state line ("committed 0.5.0 slot b at …")
	Available     string                 `protobuf:"bytes,2,opt,name=available,proto3" json:"available,omitempty"` // "0.5.1 2026-10-01" or ""
	Schedule      string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`   // "daily 03:30", "off"
	LastResult    string                 `protobuf:"bytes,4,opt,name=last_result,json=lastResult,proto3" json:"last_result,omitempty"`
	History       []string               `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"` // newest first, at most 10
	NotesStaged   bool                   `protobuf:"varint,6,opt,name=notes_staged,json=notesStaged,proto3" json:"notes_staged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplianceUpgrade) Reset() {
	*x = ApplianceUpgrade{}
	mi := &file_client_appliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceUpgrade) ProtoMessage() {}

func (x *ApplianceUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceUpgrade.ProtoReflect.Descriptor instead.
func (*ApplianceUpgrade) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{3}
}

func (x *ApplianceUpgrade) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ApplianceUpgrade) GetAvailable() string {
	if x != nil {
		return x.Available
	}
	return ""
}

func (x *ApplianceUpgrade) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *ApplianceUpgrade) GetLastResult() string {
	if x != nil {
		return x.LastResult
	}
	return ""
}

func (x *ApplianceUpgrade) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ApplianceUpgrade) GetNotesStaged() bool {
	if x != nil {
		return x.NotesStaged
	}
	return false
}

type ApplianceFirewall struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Decision         string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`                                         // on | off | undecided
	Loaded           bool                   `protobuf:"varint,2,opt,name=loaded,proto3" json:"loaded,omitempty"`                                            // the ruleset is in the kernel
	Warning          string                 `protobuf:"bytes,3,opt,name=warning,proto3" json:"warning,omitempty"`                                           // the last rejection, "" when none
	ChangePending    bool                   `protobuf:"varint,4,opt,name=change_pending,json=changePending,proto3" json:"change_pending,omitempty"`         // an unconfirmed rule change is waiting
	RevertInSeconds  int32                  `protobuf:"varint,5,opt,name=revert_in_seconds,json=revertInSeconds,proto3" json:"revert_in_seconds,omitempty"` // -1 when nothing is pending
	OpenPorts        []string               `protobuf:"bytes,6,rep,name=open_ports,json=openPorts,proto3" json:"open_ports,omitempty"`                      // data ports the listeners opened, "tcp/443"
	SshAllow         string                 `protobuf:"bytes,7,opt,name=ssh_allow,json=sshAllow,proto3" json:"ssh_allow,omitempty"`                         // management SSH allow list, "" = any source
	OperatorRules    int32                  `protobuf:"varint,8,opt,name=operator_rules,json=operatorRules,proto3" json:"operator_rules,omitempty"`
	ManagementPublic bool                   `protobuf:"varint,9,opt,name=management_public,json=managementPublic,proto3" json:"management_public,omitempty"` // the management address is publicly routable
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplianceFirewall) Reset() {
	*x = ApplianceFirewall{}
	mi := &file_client_appliance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceFirewall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceFirewall) ProtoMessage() {}

func (x *ApplianceFirewall) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceFirewall.ProtoReflect.Descriptor instead.
func (*ApplianceFirewall) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{4}
}

func (x *ApplianceFirewall) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ApplianceFirewall) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *ApplianceFirewall) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *ApplianceFirewall) GetChangePending() bool {
	if x != nil {
		return x.ChangePending
	}
	return false
}

func (x *ApplianceFirewall) GetRevertInSeconds() int32 {
	if x != nil {
		return x.RevertInSeconds
	}
	return 0
}

func (x *ApplianceFirewall) GetOpenPorts() []string {
	if x != nil {
		return x.OpenPorts
	}
	return nil
}

func (x *ApplianceFirewall) GetSshAllow() string {
	if x != nil {
		return x.SshAllow
	}
	return ""
}

func (x *ApplianceFirewall) GetOperatorRules() int32 {
	if x != nil {
		return x.OperatorRules
	}
	return 0
}

func (x *ApplianceFirewall) GetManagementPublic() bool {
	if x != nil {
		return x.ManagementPublic
	}
	return false
}

type ApplianceComplianceCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // PASS | FAIL | DEV | N/A
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Evidence      string                 `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplianceComplianceCheck) Reset() {
	*x = ApplianceComplianceCheck{}
	mi := &file_client_appliance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceComplianceCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceComplianceCheck) ProtoMessage() {}

func (x *ApplianceComplianceCheck) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceComplianceCheck.ProtoReflect.Descriptor instead.
func (*ApplianceComplianceCheck) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{5}
}

func (x *ApplianceComplianceCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplianceComplianceCheck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplianceComplianceCheck) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApplianceComplianceCheck) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type ApplianceCompliance struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Benchmark     string                      `protobuf:"bytes,1,opt,name=benchmark,proto3" json:"benchmark,omitempty"`
	CheckedAt     string                      `protobuf:"bytes,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Pass          uint32                      `protobuf:"varint,3,opt,name=pass,proto3" json:"pass,omitempty"`
	Fail          uint32                      `protobuf:"varint,4,opt,name=fail,proto3" json:"fail,omitempty"`
	Deviation     uint32                      `protobuf:"varint,5,opt,name=deviation,proto3" json:"deviation,omitempty"`
	NotApplicable uint32                      `protobuf:"varint,6,opt,name=not_applicable,json=notApplicable,proto3" json:"not_applicable,omitempty"`
	Failing       []*ApplianceComplianceCheck `protobuf:"bytes,7,rep,name=failing,proto3" json:"failing,omitempty"`  // FAIL only, at most 100
	Running       bool                        `protobuf:"varint,8,opt,name=running,proto3" json:"running,omitempty"` // a check is in progress
	NeverRun      bool                        `protobuf:"varint,9,opt,name=never_run,json=neverRun,proto3" json:"never_run,omitempty"`
	NextRun       string                      `protobuf:"bytes,10,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplianceCompliance) Reset() {
	*x = ApplianceCompliance{}
	mi := &file_client_appliance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceCompliance) ProtoMessage() {}

func (x *ApplianceCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceCompliance.ProtoReflect.Descriptor instead.
func (*ApplianceCompliance) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{6}
}

func (x *ApplianceCompliance) GetBenchmark() string {
	if x != nil {
		return x.Benchmark
	}
	return ""
}

func (x *ApplianceCompliance) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

func (x *ApplianceCompliance) GetPass() uint32 {
	if x != nil {
		return x.Pass
	}
	return 0
}

func (x *ApplianceCompliance) GetFail() uint32 {
	if x != nil {
		return x.Fail
	}
	return 0
}

func (x *ApplianceCompliance) GetDeviation() uint32 {
	if x != nil {
		return x.Deviation
	}
	return 0
}

func (x *ApplianceCompliance) GetNotApplicable() uint32 {
	if x != nil {
		return x.NotApplicable
	}
	return 0
}

func (x *ApplianceCompliance) GetFailing() []*ApplianceComplianceCheck {
	if x != nil {
		return x.Failing
	}
	return nil
}

func (x *ApplianceCompliance) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ApplianceCompliance) GetNeverRun() bool {
	if x != nil {
		return x.NeverRun
	}
	return false
}

func (x *ApplianceCompliance) GetNextRun() string {
	if x != nil {
		return x.NextRun
	}
	return ""
}

type ApplianceNetwork struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ChangeUnconfirmed   bool                   `protobuf:"varint,1,opt,name=change_unconfirmed,json=changeUnconfirmed,proto3" json:"change_unconfirmed,omitempty"` // a network change waits for `network confirm`
	RevertInSeconds     int32                  `protobuf:"varint,2,opt,name=revert_in_seconds,json=revertInSeconds,proto3" json:"revert_in_seconds,omitempty"`     // -1 when nothing waits
	LastRevert          string                 `protobuf:"bytes,3,opt,name=last_revert,json=lastRevert,proto3" json:"last_revert,omitempty"`
	MissingNics         []string               `protobuf:"bytes,4,rep,name=missing_nics,json=missingNics,proto3" json:"missing_nics,omitempty"`
	ManagementInterface string                 `protobuf:"bytes,5,opt,name=management_interface,json=managementInterface,proto3" json:"management_interface,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplianceNetwork) Reset() {
	*x = ApplianceNetwork{}
	mi := &file_client_appliance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceNetwork) ProtoMessage() {}

func (x *ApplianceNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceNetwork.ProtoReflect.Descriptor instead.
func (*ApplianceNetwork) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{7}
}

func (x *ApplianceNetwork) GetChangeUnconfirmed() bool {
	if x != nil {
		return x.ChangeUnconfirmed
	}
	return false
}

func (x *ApplianceNetwork) GetRevertInSeconds() int32 {
	if x != nil {
		return x.RevertInSeconds
	}
	return 0
}

func (x *ApplianceNetwork) GetLastRevert() string {
	if x != nil {
		return x.LastRevert
	}
	return ""
}

func (x *ApplianceNetwork) GetMissingNics() []string {
	if x != nil {
		return x.MissingNics
	}
	return nil
}

func (x *ApplianceNetwork) GetManagementInterface() string {
	if x != nil {
		return x.ManagementInterface
	}
	return ""
}

type ApplianceComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Bundled       string                 `protobuf:"bytes,3,opt,name=bundled,proto3" json:"bundled,omitempty"` // the version this release ships
	Pinned        bool                   `protobuf:"varint,4,opt,name=pinned,proto3" json:"pinned,omitempty"`  // installed by the operator, kept across upgrades
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Mismatch      bool                   `protobuf:"varint,6,opt,name=mismatch,proto3" json:"mismatch,omitempty"` // the binary on disk does not match its record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplianceComponent) Reset() {
	*x = ApplianceComponent{}
	mi := &file_client_appliance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceComponent) ProtoMessage() {}

func (x *ApplianceComponent) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceComponent.ProtoReflect.Descriptor instead.
func (*ApplianceComponent) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{8}
}

func (x *ApplianceComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplianceComponent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplianceComponent) GetBundled() string {
	if x != nil {
		return x.Bundled
	}
	return ""
}

func (x *ApplianceComponent) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ApplianceComponent) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ApplianceComponent) GetMismatch() bool {
	if x != nil {
		return x.Mismatch
	}
	return false
}

type ApplianceArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"` // 32 lowercase hex
	Kind          ApplianceArtifactKind  `protobuf:"varint,2,opt,name=kind,proto3,enum=client.ApplianceArtifactKind" json:"kind,omitempty"`
	State         ApplianceArtifactState `protobuf:"varint,3,opt,name=state,proto3,enum=client.ApplianceArtifactState" json:"state,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplianceArtifact) Reset() {
	*x = ApplianceArtifact{}
	mi := &file_client_appliance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceArtifact) ProtoMessage() {}

func (x *ApplianceArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceArtifact.ProtoReflect.Descriptor instead.
func (*ApplianceArtifact) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{9}
}

func (x *ApplianceArtifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ApplianceArtifact) GetKind() ApplianceArtifactKind {
	if x != nil {
		return x.Kind
	}
	return ApplianceArtifactKind_APPLIANCE_ARTIFACT_KIND_UNSPECIFIED
}

func (x *ApplianceArtifact) GetState() ApplianceArtifactState {
	if x != nil {
		return x.State
	}
	return ApplianceArtifactState_APPLIANCE_ARTIFACT_STATE_UNSPECIFIED
}

func (x *ApplianceArtifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ApplianceArtifact) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ApplianceArtifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ApplianceArtifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApplianceArtifact) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ApplianceArtifact) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApplianceStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Schema         string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // the producer's document schema, "elchi.appliance.status/1"
	CollectedAt    string                 `protobuf:"bytes,2,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Product        string                 `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	OsVersion      string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Hostname       string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	UpgradedFrom   string                 `protobuf:"bytes,6,opt,name=upgraded_from,json=upgradedFrom,proto3" json:"upgraded_from,omitempty"`
	Uptime         string                 `protobuf:"bytes,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	RebootRequired bool                   `protobuf:"varint,8,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	BootSlots      *ApplianceBootSlots    `protobuf:"bytes,9,opt,name=boot_slots,json=bootSlots,proto3" json:"boot_slots,omitempty"`
	Upgrade        *ApplianceUpgrade      `protobuf:"bytes,10,opt,name=upgrade,proto3" json:"upgrade,omitempty"`
	Health         *ApplianceHealth       `protobuf:"bytes,11,opt,name=health,proto3" json:"health,omitempty"`
	Firewall       *ApplianceFirewall     `protobuf:"bytes,12,opt,name=firewall,proto3" json:"firewall,omitempty"`
	Compliance     *ApplianceCompliance   `protobuf:"bytes,13,opt,name=compliance,proto3" json:"compliance,omitempty"`
	Network        *ApplianceNetwork      `protobuf:"bytes,14,opt,name=network,proto3" json:"network,omitempty"`
	Components     []*ApplianceComponent  `protobuf:"bytes,15,rep,name=components,proto3" json:"components,omitempty"`
	Artifacts      []*ApplianceArtifact   `protobuf:"bytes,16,rep,name=artifacts,proto3" json:"artifacts,omitempty"`                                                                 // exports present on the appliance
	Unavailable    []string               `protobuf:"bytes,17,rep,name=unavailable,proto3" json:"unavailable,omitempty"`                                                             // sections that could not be read, "firewall: <why>"
	Info           map[string]string      `protobuf:"bytes,18,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // further facts; the UI shows keys it does not know
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplianceStatus) Reset() {
	*x = ApplianceStatus{}
	mi := &file_client_appliance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplianceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplianceStatus) ProtoMessage() {}

func (x *ApplianceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_appliance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplianceStatus.ProtoReflect.Descriptor instead.
func (*ApplianceStatus) Descriptor() ([]byte, []int) {
	return file_client_appliance_proto_rawDescGZIP(), []int{10}
}

func (x *ApplianceStatus) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ApplianceStatus) GetCollectedAt() string {
	if x != nil {
		return x.CollectedAt
	}
	return ""
}

func (x *ApplianceStatus) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ApplianceStatus) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *ApplianceStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ApplianceStatus) GetUpgradedFrom() string {
	if x != nil {
		return x.UpgradedFrom
	}
	return ""
}

func (x *ApplianceStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *ApplianceStatus) GetRebootRequired() bool {
	if x != nil {
		return x.RebootRequired
	}
	return false
}

func (x *ApplianceStatus) GetBootSlots() *ApplianceBootSlots {
	if x != nil {
		return x.BootSlots
	}
	return nil
}

func (x *ApplianceStatus) GetUpgrade() *ApplianceUpgrade {
	if x != nil {
		return x.Upgrade
	}
	return nil
}

func (x *ApplianceStatus) GetHealth() *ApplianceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *ApplianceStatus) GetFirewall() *ApplianceFirewall {
	if x != nil {
		return x.Firewall
	}
	return nil
}

func (x *ApplianceStatus) GetCompliance() *ApplianceCompliance {
	if x != nil {
		return x.Compliance
	}
	return nil
}

func (x *ApplianceStatus) GetNetwork() *ApplianceNetwork {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ApplianceStatus) GetComponents() []*ApplianceComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ApplianceStatus) GetArtifacts() []*ApplianceArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ApplianceStatus) GetUnavailable() []string {
	if x != nil {
		return x.Unavailable
	}
	return nil
}

func (x *ApplianceStatus) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_client_appliance_proto protoreflect.FileDescriptor

const file_client_appliance_proto_rawDesc = "" +
	"\n" +
	"\x16client/appliance.proto\x12\x06client\"o\n" +
	"\x13ApplianceHealthItem\x12\x12\n" +
	"\x04area\x18\x01 \x01(\tR\x04area\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\xdd\x01\n" +
	"\x0fApplianceHealth\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x01 \x01(\tR\tcheckedAt\x12\x14\n" +
	"\x05worst\x18\x02 \x01(\tR\x05worst\x12\x1f\n" +
	"\vworst_level\x18\x03 \x01(\x05R\n" +
	"worstLevel\x121\n" +
	"\x05items\x18\x04 \x03(\v2\x1b.client.ApplianceHealthItemR\x05items\x12\x18\n" +
	"\amissing\x18\x05 \x03(\tR\amissing\x12'\n" +
	"\x0felapsed_seconds\x18\x06 \x01(\x01R\x0eelapsedSeconds\"\x97\x01\n" +
	"\x12ApplianceBootSlots\x12\x18\n" +
	"\arunning\x18\x01 \x01(\tR\arunning\x12\x1c\n" +
	"\tcommitted\x18\x02 \x01(\tR\tcommitted\x12\x1b\n" +
	"\tnext_boot\x18\x03 \x01(\tR\bnextBoot\x12\x15\n" +
	"\x06slot_a\x18\x04 \x01(\tR\x05slotA\x12\x15\n" +
	"\x06slot_b\x18\x05 \x01(\tR\x05slotB\"\xc0\x01\n" +
	"\x10ApplianceUpgrade\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\tR\tavailable\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x1f\n" +
	"\vlast_result\x18\x04 \x01(\tR\n" +
	"lastResult\x12\x18\n" +
	"\ahistory\x18\x05 \x03(\tR\ahistory\x12!\n" +
	"\fnotes_staged\x18\x06 \x01(\bR\vnotesStaged\"\xc4\x02\n" +
	"\x11ApplianceFirewall\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x16\n" +
	"\x06loaded\x18\x02 \x01(\bR\x06loaded\x12\x18\n" +
	"\awarning\x18\x03 \x01(\tR\awarning\x12%\n" +
	"\x0echange_pending\x18\x04 \x01(\bR\rchangePending\x12*\n" +
	"\x11revert_in_seconds\x18\x05 \x01(\x05R\x0frevertInSeconds\x12\x1d\n" +
	"\n" +
	"open_ports\x18\x06 \x03(\tR\topenPorts\x12\x1b\n" +
	"\tssh_allow\x18\a \x01(\tR\bsshAllow\x12%\n" +
	"\x0eoperator_rules\x18\b \x01(\x05R\roperatorRules\x12+\n" +
	"\x11management_public\x18\t \x01(\bR\x10managementPublic\"t\n" +
	"\x18ApplianceComplianceCheck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bevidence\x18\x04 \x01(\tR\bevidence\"\xcd\x02\n" +
	"\x13ApplianceCompliance\x12\x1c\n" +
	"\tbenchmark\x18\x01 \x01(\tR\tbenchmark\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\tR\tcheckedAt\x12\x12\n" +
	"\x04pass\x18\x03 \x01(\rR\x04pass\x12\x12\n" +
	"\x04fail\x18\x04 \x01(\rR\x04fail\x12\x1c\n" +
	"\tdeviation\x18\x05 \x01(\rR\tdeviation\x12%\n" +
	"\x0enot_applicable\x18\x06 \x01(\rR\rnotApplicable\x12:\n" +
	"\afailing\x18\a \x03(\v2 .client.ApplianceComplianceCheckR\afailing\x12\x18\n" +
	"\arunning\x18\b \x01(\bR\arunning\x12\x1b\n" +
	"\tnever_run\x18\t \x01(\bR\bneverRun\x12\x19\n" +
	"\bnext_run\x18\n" +
	" \x01(\tR\anextRun\"\xe4\x01\n" +
	"\x10ApplianceNetwork\x12-\n" +
	"\x12change_unconfirmed\x18\x01 \x01(\bR\x11changeUnconfirmed\x12*\n" +
	"\x11revert_in_seconds\x18\x02 \x01(\x05R\x0frevertInSeconds\x12\x1f\n" +
	"\vlast_revert\x18\x03 \x01(\tR\n" +
	"lastRevert\x12!\n" +
	"\fmissing_nics\x18\x04 \x03(\tR\vmissingNics\x121\n" +
	"\x14management_interface\x18\x05 \x01(\tR\x13managementInterface\"\xa8\x01\n" +
	"\x12ApplianceComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\abundled\x18\x03 \x01(\tR\abundled\x12\x16\n" +
	"\x06pinned\x18\x04 \x01(\bR\x06pinned\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12\x1a\n" +
	"\bmismatch\x18\x06 \x01(\bR\bmismatch\"\xb9\x02\n" +
	"\x11ApplianceArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.client.ApplianceArtifactKindR\x04kind\x124\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1e.client.ApplianceArtifactStateR\x05state\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\xd6\x06\n" +
	"\x0fApplianceStatus\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12!\n" +
	"\fcollected_at\x18\x02 \x01(\tR\vcollectedAt\x12\x18\n" +
	"\aproduct\x18\x03 \x01(\tR\aproduct\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12#\n" +
	"\rupgraded_from\x18\x06 \x01(\tR\fupgradedFrom\x12\x16\n" +
	"\x06uptime\x18\a \x01(\tR\x06uptime\x12'\n" +
	"\x0freboot_required\x18\b \x01(\bR\x0erebootRequired\x129\n" +
	"\n" +
	"boot_slots\x18\t \x01(\v2\x1a.client.ApplianceBootSlotsR\tbootSlots\x122\n" +
	"\aupgrade\x18\n" +
	" \x01(\v2\x18.client.ApplianceUpgradeR\aupgrade\x12/\n" +
	"\x06health\x18\v \x01(\v2\x17.client.ApplianceHealthR\x06health\x125\n" +
	"\bfirewall\x18\f \x01(\v2\x19.client.ApplianceFirewallR\bfirewall\x12;\n" +
	"\n" +
	"compliance\x18\r \x01(\v2\x1b.client.ApplianceComplianceR\n" +
	"compliance\x122\n" +
	"\anetwork\x18\x0e \x01(\v2\x18.client.ApplianceNetworkR\anetwork\x12:\n" +
	"\n" +
	"components\x18\x0f \x03(\v2\x1a.client.ApplianceComponentR\n" +
	"components\x127\n" +
	"\tartifacts\x18\x10 \x03(\v2\x19.client.ApplianceArtifactR\tartifacts\x12 \n" +
	"\vunavailable\x18\x11 \x03(\tR\vunavailable\x125\n" +
	"\x04info\x18\x12 \x03(\v2!.client.ApplianceStatus.InfoEntryR\x04info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8e\x01\n" +
	"\x15ApplianceArtifactKind\x12'\n" +
	"#APPLIANCE_ARTIFACT_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!APPLIANCE_ARTIFACT_SUPPORT_BUNDLE\x10\x01\x12%\n" +
	"!APPLIANCE_ARTIFACT_CONFIG_ARCHIVE\x10\x02*\xbf\x01\n" +
	"\x16ApplianceArtifactState\x12(\n" +
	"$APPLIANCE_ARTIFACT_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAPPLIANCE_ARTIFACT_RUNNING\x10\x01\x12\x1c\n" +
	"\x18APPLIANCE_ARTIFACT_READY\x10\x02\x12\x1d\n" +
	"\x19APPLIANCE_ARTIFACT_FAILED\x10\x03\x12\x1e\n" +
	"\x1aAPPLIANCE_ARTIFACT_EXPIRED\x10\x04B0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_appliance_proto_rawDescOnce sync.Once
	file_client_appliance_proto_rawDescData []byte
)

func file_client_appliance_proto_rawDescGZIP() []byte {
	file_client_appliance_proto_rawDescOnce.Do(func() {
		file_client_appliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_appliance_proto_rawDesc), len(file_client_appliance_proto_rawDesc)))
	})
	return file_client_appliance_proto_rawDescData
}

var file_client_appliance_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_client_appliance_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_client_appliance_proto_goTypes = []any{
	(ApplianceArtifactKind)(0),       // 0: client.ApplianceArtifactKind
	(ApplianceArtifactState)(0),      // 1: client.ApplianceArtifactState
	(*ApplianceHealthItem)(nil),      // 2: client.ApplianceHealthItem
	(*ApplianceHealth)(nil),          // 3: client.ApplianceHealth
	(*ApplianceBootSlots)(nil),       // 4: client.ApplianceBootSlots
	(*ApplianceUpgrade)(nil),         // 5: client.ApplianceUpgrade
	(*ApplianceFirewall)(nil),        // 6: client.ApplianceFirewall
	(*ApplianceComplianceCheck)(nil), // 7: client.ApplianceComplianceCheck
	(*ApplianceCompliance)(nil),      // 8: client.ApplianceCompliance
	(*ApplianceNetwork)(nil),         // 9: client.ApplianceNetwork
	(*ApplianceComponent)(nil),       // 10: client.ApplianceComponent
	(*ApplianceArtifact)(nil),        // 11: client.ApplianceArtifact
	(*ApplianceStatus)(nil),          // 12: client.ApplianceStatus
	nil,                              // 13: client.ApplianceStatus.InfoEntry
}
var file_client_appliance_proto_depIdxs = []int32{
	2,  // 0: client.ApplianceHealth.items:type_name -> client.ApplianceHealthItem
	7,  // 1: client.ApplianceCompliance.failing:type_name -> client.ApplianceComplianceCheck
	0,  // 2: client.ApplianceArtifact.kind:type_name -> client.ApplianceArtifactKind
	1,  // 3: client.ApplianceArtifact.state:type_name -> client.ApplianceArtifactState
	4,  // 4: client.ApplianceStatus.boot_slots:type_name -> client.ApplianceBootSlots
	5,  // 5: client.ApplianceStatus.upgrade:type_name -> client.ApplianceUpgrade
	3,  // 6: client.ApplianceStatus.health:type_name -> client.ApplianceHealth
	6,  // 7: client.ApplianceStatus.firewall:type_name -> client.ApplianceFirewall
	8,  // 8: client.ApplianceStatus.compliance:type_name -> client.ApplianceCompliance
	9,  // 9: client.ApplianceStatus.network:type_name -> client.ApplianceNetwork
	10, // 10: client.ApplianceStatus.components:type_name -> client.ApplianceComponent
	11, // 11: client.ApplianceStatus.artifacts:type_name -> client.ApplianceArtifact
	13, // 12: client.ApplianceStatus.info:type_name -> client.ApplianceStatus.InfoEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_client_appliance_proto_init() }
func file_client_appliance_proto_init() {
	if File_client_appliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_appliance_proto_rawDesc), len(file_client_appliance_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_appliance_proto_goTypes,
		DependencyIndexes: file_client_appliance_proto_depIdxs,
		EnumInfos:         file_client_appliance_proto_enumTypes,
		MessageInfos:      file_client_appliance_proto_msgTypes,
	}.Build()
	File_client_appliance_proto = out.File
	file_client_appliance_proto_goTypes = nil
	file_client_appliance_proto_depIdxs = nil
}
