// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: client/controller.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerService_RegisterController_FullMethodName     = "/client.ControllerService/RegisterController"
	ControllerService_GetClientLocation_FullMethodName      = "/client.ControllerService/GetClientLocation"
	ControllerService_SetClientLocation_FullMethodName      = "/client.ControllerService/SetClientLocation"
	ControllerService_ForwardCommand_FullMethodName         = "/client.ControllerService/ForwardCommand"
	ControllerService_RequestClientRefresh_FullMethodName   = "/client.ControllerService/RequestClientRefresh"
	ControllerService_IsControllerRegistered_FullMethodName = "/client.ControllerService/IsControllerRegistered"
	ControllerService_BulkSetClientLocations_FullMethodName = "/client.ControllerService/BulkSetClientLocations"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	// RegisterController registers a controller with the registry
	RegisterController(ctx context.Context, in *ControllerInfo, opts ...grpc.CallOption) (*ControllerResponse, error)
	// GetClientLocation finds which controller a client is connected to
	GetClientLocation(ctx context.Context, in *ClientLocationRequest, opts ...grpc.CallOption) (*ClientLocationResponse, error)
	// SetClientLocation sets where a client is connected
	SetClientLocation(ctx context.Context, in *SetClientLocationRequest, opts ...grpc.CallOption) (*SetClientLocationResponse, error)
	// ForwardCommand forwards a command to the appropriate controller
	ForwardCommand(ctx context.Context, in *ForwardCommandRequest, opts ...grpc.CallOption) (*ForwardCommandResponse, error)
	RequestClientRefresh(ctx context.Context, in *ClientRefreshRequest, opts ...grpc.CallOption) (*ClientRefreshResponse, error)
	IsControllerRegistered(ctx context.Context, in *IsControllerRegisteredRequest, opts ...grpc.CallOption) (*IsControllerRegisteredResponse, error)
	BulkSetClientLocations(ctx context.Context, in *BulkSetClientLocationsRequest, opts ...grpc.CallOption) (*BulkSetClientLocationsResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) RegisterController(ctx context.Context, in *ControllerInfo, opts ...grpc.CallOption) (*ControllerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControllerResponse)
	err := c.cc.Invoke(ctx, ControllerService_RegisterController_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetClientLocation(ctx context.Context, in *ClientLocationRequest, opts ...grpc.CallOption) (*ClientLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientLocationResponse)
	err := c.cc.Invoke(ctx, ControllerService_GetClientLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) SetClientLocation(ctx context.Context, in *SetClientLocationRequest, opts ...grpc.CallOption) (*SetClientLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetClientLocationResponse)
	err := c.cc.Invoke(ctx, ControllerService_SetClientLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ForwardCommand(ctx context.Context, in *ForwardCommandRequest, opts ...grpc.CallOption) (*ForwardCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardCommandResponse)
	err := c.cc.Invoke(ctx, ControllerService_ForwardCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) RequestClientRefresh(ctx context.Context, in *ClientRefreshRequest, opts ...grpc.CallOption) (*ClientRefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientRefreshResponse)
	err := c.cc.Invoke(ctx, ControllerService_RequestClientRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) IsControllerRegistered(ctx context.Context, in *IsControllerRegisteredRequest, opts ...grpc.CallOption) (*IsControllerRegisteredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsControllerRegisteredResponse)
	err := c.cc.Invoke(ctx, ControllerService_IsControllerRegistered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) BulkSetClientLocations(ctx context.Context, in *BulkSetClientLocationsRequest, opts ...grpc.CallOption) (*BulkSetClientLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkSetClientLocationsResponse)
	err := c.cc.Invoke(ctx, ControllerService_BulkSetClientLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
type ControllerServiceServer interface {
	// RegisterController registers a controller with the registry
	RegisterController(context.Context, *ControllerInfo) (*ControllerResponse, error)
	// GetClientLocation finds which controller a client is connected to
	GetClientLocation(context.Context, *ClientLocationRequest) (*ClientLocationResponse, error)
	// SetClientLocation sets where a client is connected
	SetClientLocation(context.Context, *SetClientLocationRequest) (*SetClientLocationResponse, error)
	// ForwardCommand forwards a command to the appropriate controller
	ForwardCommand(context.Context, *ForwardCommandRequest) (*ForwardCommandResponse, error)
	RequestClientRefresh(context.Context, *ClientRefreshRequest) (*ClientRefreshResponse, error)
	IsControllerRegistered(context.Context, *IsControllerRegisteredRequest) (*IsControllerRegisteredResponse, error)
	BulkSetClientLocations(context.Context, *BulkSetClientLocationsRequest) (*BulkSetClientLocationsResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) RegisterController(context.Context, *ControllerInfo) (*ControllerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterController not implemented")
}
func (UnimplementedControllerServiceServer) GetClientLocation(context.Context, *ClientLocationRequest) (*ClientLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientLocation not implemented")
}
func (UnimplementedControllerServiceServer) SetClientLocation(context.Context, *SetClientLocationRequest) (*SetClientLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetClientLocation not implemented")
}
func (UnimplementedControllerServiceServer) ForwardCommand(context.Context, *ForwardCommandRequest) (*ForwardCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardCommand not implemented")
}
func (UnimplementedControllerServiceServer) RequestClientRefresh(context.Context, *ClientRefreshRequest) (*ClientRefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestClientRefresh not implemented")
}
func (UnimplementedControllerServiceServer) IsControllerRegistered(context.Context, *IsControllerRegisteredRequest) (*IsControllerRegisteredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsControllerRegistered not implemented")
}
func (UnimplementedControllerServiceServer) BulkSetClientLocations(context.Context, *BulkSetClientLocationsRequest) (*BulkSetClientLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkSetClientLocations not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call pancis, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_RegisterController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).RegisterController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_RegisterController_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).RegisterController(ctx, req.(*ControllerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetClientLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetClientLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetClientLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetClientLocation(ctx, req.(*ClientLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_SetClientLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClientLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).SetClientLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_SetClientLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).SetClientLocation(ctx, req.(*SetClientLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ForwardCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ForwardCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ForwardCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ForwardCommand(ctx, req.(*ForwardCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_RequestClientRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).RequestClientRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_RequestClientRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).RequestClientRefresh(ctx, req.(*ClientRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_IsControllerRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsControllerRegisteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).IsControllerRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_IsControllerRegistered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).IsControllerRegistered(ctx, req.(*IsControllerRegisteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_BulkSetClientLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkSetClientLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).BulkSetClientLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_BulkSetClientLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).BulkSetClientLocations(ctx, req.(*BulkSetClientLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterController",
			Handler:    _ControllerService_RegisterController_Handler,
		},
		{
			MethodName: "GetClientLocation",
			Handler:    _ControllerService_GetClientLocation_Handler,
		},
		{
			MethodName: "SetClientLocation",
			Handler:    _ControllerService_SetClientLocation_Handler,
		},
		{
			MethodName: "ForwardCommand",
			Handler:    _ControllerService_ForwardCommand_Handler,
		},
		{
			MethodName: "RequestClientRefresh",
			Handler:    _ControllerService_RequestClientRefresh_Handler,
		},
		{
			MethodName: "IsControllerRegistered",
			Handler:    _ControllerService_IsControllerRegistered_Handler,
		},
		{
			MethodName: "BulkSetClientLocations",
			Handler:    _ControllerService_BulkSetClientLocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/controller.proto",
}
