// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/filebeat.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Filebeat input configuration
type FilebeatInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`        // Input type (e.g., "filestream")
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"` // Enable/disable input
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`            // Unique input ID (e.g., "elchi-logs")
	Paths         []string               `protobuf:"bytes,4,rep,name=paths,proto3" json:"paths,omitempty"`      // Log file paths (e.g., ["/var/log/elchi/*.log"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilebeatInput) Reset() {
	*x = FilebeatInput{}
	mi := &file_client_filebeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilebeatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilebeatInput) ProtoMessage() {}

func (x *FilebeatInput) ProtoReflect() protoreflect.Message {
	mi := &file_client_filebeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilebeatInput.ProtoReflect.Descriptor instead.
func (*FilebeatInput) Descriptor() ([]byte, []int) {
	return file_client_filebeat_proto_rawDescGZIP(), []int{0}
}

func (x *FilebeatInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FilebeatInput) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FilebeatInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilebeatInput) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// Timestamp processor configuration
type TimestampProcessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`     // Field to parse (e.g., "message")
	Layouts       []string               `protobuf:"bytes,2,rep,name=layouts,proto3" json:"layouts,omitempty"` // Time layouts (e.g., ["[2006-01-02 15:04:05.000]"])
	Test          []string               `protobuf:"bytes,3,rep,name=test,proto3" json:"test,omitempty"`       // Test patterns for validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampProcessor) Reset() {
	*x = TimestampProcessor{}
	mi := &file_client_filebeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampProcessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampProcessor) ProtoMessage() {}

func (x *TimestampProcessor) ProtoReflect() protoreflect.Message {
	mi := &file_client_filebeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampProcessor.ProtoReflect.Descriptor instead.
func (*TimestampProcessor) Descriptor() ([]byte, []int) {
	return file_client_filebeat_proto_rawDescGZIP(), []int{1}
}

func (x *TimestampProcessor) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TimestampProcessor) GetLayouts() []string {
	if x != nil {
		return x.Layouts
	}
	return nil
}

func (x *TimestampProcessor) GetTest() []string {
	if x != nil {
		return x.Test
	}
	return nil
}

// Drop fields processor configuration
type DropFieldsProcessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"` // Fields to drop (e.g., ["agent", "input"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropFieldsProcessor) Reset() {
	*x = DropFieldsProcessor{}
	mi := &file_client_filebeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropFieldsProcessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropFieldsProcessor) ProtoMessage() {}

func (x *DropFieldsProcessor) ProtoReflect() protoreflect.Message {
	mi := &file_client_filebeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropFieldsProcessor.ProtoReflect.Descriptor instead.
func (*DropFieldsProcessor) Descriptor() ([]byte, []int) {
	return file_client_filebeat_proto_rawDescGZIP(), []int{2}
}

func (x *DropFieldsProcessor) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FilebeatOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*FilebeatOutput_Elasticsearch
	//	*FilebeatOutput_Logstash
	Output        isFilebeatOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilebeatOutput) Reset() {
	*x = FilebeatOutput{}
	mi := &file_client_filebeat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilebeatOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilebeatOutput) ProtoMessage() {}

func (x *FilebeatOutput) ProtoReflect() protoreflect.Message {
	mi := &file_client_filebeat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilebeatOutput.ProtoReflect.Descriptor instead.
func (*FilebeatOutput) Descriptor() ([]byte, []int) {
	return file_client_filebeat_proto_rawDescGZIP(), []int{3}
}

func (x *FilebeatOutput) GetOutput() isFilebeatOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *FilebeatOutput) GetElasticsearch() *ElasticsearchOutput {
	if x != nil {
		if x, ok := x.Output.(*FilebeatOutput_Elasticsearch); ok {
			return x.Elasticsearch
		}
	}
	return nil
}

func (x *FilebeatOutput) GetLogstash() *LogstashOutput {
	if x != nil {
		if x, ok := x.Output.(*FilebeatOutput_Logstash); ok {
			return x.Logstash
		}
	}
	return nil
}

type isFilebeatOutput_Output interface {
	isFilebeatOutput_Output()
}

type FilebeatOutput_Elasticsearch struct {
	Elasticsearch *ElasticsearchOutput `protobuf:"bytes,1,opt,name=elasticsearch,proto3,oneof"`
}

type FilebeatOutput_Logstash struct {
	Logstash *LogstashOutput `protobuf:"bytes,2,opt,name=logstash,proto3,oneof"`
}

func (*FilebeatOutput_Elasticsearch) isFilebeatOutput_Output() {}

func (*FilebeatOutput_Logstash) isFilebeatOutput_Output() {}

type ElasticsearchOutput struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Hosts       []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`              // Elasticsearch hosts (e.g., ["http://elasticsearch:9200"])
	Loadbalance bool                   `protobuf:"varint,2,opt,name=loadbalance,proto3" json:"loadbalance,omitempty"` // Enable load balancing across hosts
	// Authentication method (mutually exclusive)
	//
	// Types that are valid to be assigned to Auth:
	//
	//	*ElasticsearchOutput_ApiKey
	//	*ElasticsearchOutput_BasicAuth
	Auth          isElasticsearchOutput_Auth `protobuf_oneof:"auth"`
	SkipSslVerify bool                       `protobuf:"varint,5,opt,name=skip_ssl_verify,json=skipSslVerify,proto3" json:"skip_ssl_verify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElasticsearchOutput) Reset() {
	*x = ElasticsearchOutput{}
	mi := &file_client_filebeat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElasticsearchOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticsearchOutput) ProtoMessage() {}

func (x *ElasticsearchOutput) ProtoReflect() protoreflect.Message {
	mi := &file_client_filebeat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticsearchOutput.ProtoReflect.Descriptor instead.
func (*ElasticsearchOutput) Descriptor() ([]byte, []int) {
	return file_client_filebeat_proto_rawDescGZIP(), []int{4}
}

func (x *ElasticsearchOutput) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ElasticsearchOutput) GetLoadbalance() bool {
	if x != nil {
		return x.Loadbalance
	}
	return false
}

func (x *ElasticsearchOutput) GetAuth() isElasticsearchOutput_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ElasticsearchOutput) GetApiKey() string {
	if x != nil {
		if x, ok := x.Auth.(*ElasticsearchOutput_ApiKey); ok {
			return x.ApiKey
		}
	}
	return ""
}

func (x *ElasticsearchOutput) GetBasicAuth() *BasicAuth {
	if x != nil {
		if x, ok := x.Auth.(*ElasticsearchOutput_BasicAuth); ok {
			return x.BasicAuth
		}
	}
	return nil
}

func (x *ElasticsearchOutput) GetSkipSslVerify() bool {
	if x != nil {
		return x.SkipSslVerify
	}
	return false
}

type isElasticsearchOutput_Auth interface {
	isElasticsearchOutput_Auth()
}

type ElasticsearchOutput_ApiKey struct {
	ApiKey string `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3,oneof"` // API key format: "id:api_key"
}

type ElasticsearchOutput_BasicAuth struct {
	BasicAuth *BasicAuth `protobuf:"bytes,4,opt,name=basic_auth,json=basicAuth,proto3,oneof"` // Username + password authentication
}

func (*ElasticsearchOutput_ApiKey) isElasticsearchOutput_Auth() {}

func (*ElasticsearchOutput_BasicAuth) isElasticsearchOutput_Auth() {}

type BasicAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	mi := &file_client_filebeat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_client_filebeat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuth.ProtoReflect.Descriptor instead.
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return file_client_filebeat_proto_rawDescGZIP(), []int{5}
}

func (x *BasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LogstashOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`              // Logstash hosts (e.g., ["logstash:5044"])
	Loadbalance   bool                   `protobuf:"varint,3,opt,name=loadbalance,proto3" json:"loadbalance,omitempty"` // Enable load balancing across hosts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogstashOutput) Reset() {
	*x = LogstashOutput{}
	mi := &file_client_filebeat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogstashOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogstashOutput) ProtoMessage() {}

func (x *LogstashOutput) ProtoReflect() protoreflect.Message {
	mi := &file_client_filebeat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogstashOutput.ProtoReflect.Descriptor instead.
func (*LogstashOutput) Descriptor() ([]byte, []int) {
	return file_client_filebeat_proto_rawDescGZIP(), []int{6}
}

func (x *LogstashOutput) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *LogstashOutput) GetLoadbalance() bool {
	if x != nil {
		return x.Loadbalance
	}
	return false
}

var File_client_filebeat_proto protoreflect.FileDescriptor

const file_client_filebeat_proto_rawDesc = "" +
	"\n" +
	"\x15client/filebeat.proto\x12\x06client\"c\n" +
	"\rFilebeatInput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x14\n" +
	"\x05paths\x18\x04 \x03(\tR\x05paths\"X\n" +
	"\x12TimestampProcessor\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\alayouts\x18\x02 \x03(\tR\alayouts\x12\x12\n" +
	"\x04test\x18\x03 \x03(\tR\x04test\"-\n" +
	"\x13DropFieldsProcessor\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\"\x95\x01\n" +
	"\x0eFilebeatOutput\x12C\n" +
	"\relasticsearch\x18\x01 \x01(\v2\x1b.client.ElasticsearchOutputH\x00R\relasticsearch\x124\n" +
	"\blogstash\x18\x02 \x01(\v2\x16.client.LogstashOutputH\x00R\blogstashB\b\n" +
	"\x06output\"\xcc\x01\n" +
	"\x13ElasticsearchOutput\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12 \n" +
	"\vloadbalance\x18\x02 \x01(\bR\vloadbalance\x12\x19\n" +
	"\aapi_key\x18\x03 \x01(\tH\x00R\x06apiKey\x122\n" +
	"\n" +
	"basic_auth\x18\x04 \x01(\v2\x11.client.BasicAuthH\x00R\tbasicAuth\x12&\n" +
	"\x0fskip_ssl_verify\x18\x05 \x01(\bR\rskipSslVerifyB\x06\n" +
	"\x04auth\"C\n" +
	"\tBasicAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"H\n" +
	"\x0eLogstashOutput\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12 \n" +
	"\vloadbalance\x18\x03 \x01(\bR\vloadbalanceB0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_filebeat_proto_rawDescOnce sync.Once
	file_client_filebeat_proto_rawDescData []byte
)

func file_client_filebeat_proto_rawDescGZIP() []byte {
	file_client_filebeat_proto_rawDescOnce.Do(func() {
		file_client_filebeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_filebeat_proto_rawDesc), len(file_client_filebeat_proto_rawDesc)))
	})
	return file_client_filebeat_proto_rawDescData
}

var file_client_filebeat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_filebeat_proto_goTypes = []any{
	(*FilebeatInput)(nil),       // 0: client.FilebeatInput
	(*TimestampProcessor)(nil),  // 1: client.TimestampProcessor
	(*DropFieldsProcessor)(nil), // 2: client.DropFieldsProcessor
	(*FilebeatOutput)(nil),      // 3: client.FilebeatOutput
	(*ElasticsearchOutput)(nil), // 4: client.ElasticsearchOutput
	(*BasicAuth)(nil),           // 5: client.BasicAuth
	(*LogstashOutput)(nil),      // 6: client.LogstashOutput
}
var file_client_filebeat_proto_depIdxs = []int32{
	4, // 0: client.FilebeatOutput.elasticsearch:type_name -> client.ElasticsearchOutput
	6, // 1: client.FilebeatOutput.logstash:type_name -> client.LogstashOutput
	5, // 2: client.ElasticsearchOutput.basic_auth:type_name -> client.BasicAuth
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_client_filebeat_proto_init() }
func file_client_filebeat_proto_init() {
	if File_client_filebeat_proto != nil {
		return
	}
	file_client_filebeat_proto_msgTypes[3].OneofWrappers = []any{
		(*FilebeatOutput_Elasticsearch)(nil),
		(*FilebeatOutput_Logstash)(nil),
	}
	file_client_filebeat_proto_msgTypes[4].OneofWrappers = []any{
		(*ElasticsearchOutput_ApiKey)(nil),
		(*ElasticsearchOutput_BasicAuth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_filebeat_proto_rawDesc), len(file_client_filebeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_filebeat_proto_goTypes,
		DependencyIndexes: file_client_filebeat_proto_depIdxs,
		MessageInfos:      file_client_filebeat_proto_msgTypes,
	}.Build()
	File_client_filebeat_proto = out.File
	file_client_filebeat_proto_goTypes = nil
	file_client_filebeat_proto_depIdxs = nil
}
