// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/identity.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ClientName    string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_client_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_client_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_client_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Identity) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *Identity) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

var File_client_identity_proto protoreflect.FileDescriptor

const file_client_identity_proto_rawDesc = "" +
	"\n" +
	"\x15client/identity.proto\x12\x06client\"m\n" +
	"\bIdentity\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientNameB0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_identity_proto_rawDescOnce sync.Once
	file_client_identity_proto_rawDescData []byte
)

func file_client_identity_proto_rawDescGZIP() []byte {
	file_client_identity_proto_rawDescOnce.Do(func() {
		file_client_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_identity_proto_rawDesc), len(file_client_identity_proto_rawDesc)))
	})
	return file_client_identity_proto_rawDescData
}

var file_client_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_client_identity_proto_goTypes = []any{
	(*Identity)(nil), // 0: client.Identity
}
var file_client_identity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_identity_proto_init() }
func file_client_identity_proto_init() {
	if File_client_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_identity_proto_rawDesc), len(file_client_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_identity_proto_goTypes,
		DependencyIndexes: file_client_identity_proto_depIdxs,
		MessageInfos:      file_client_identity_proto_msgTypes,
	}.Build()
	File_client_identity_proto = out.File
	file_client_identity_proto_goTypes = nil
	file_client_identity_proto_depIdxs = nil
}
