// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/network.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteOperation_Action int32

const (
	RouteOperation_ADD     RouteOperation_Action = 0
	RouteOperation_DELETE  RouteOperation_Action = 1
	RouteOperation_REPLACE RouteOperation_Action = 2
)

// Enum value maps for RouteOperation_Action.
var (
	RouteOperation_Action_name = map[int32]string{
		0: "ADD",
		1: "DELETE",
		2: "REPLACE",
	}
	RouteOperation_Action_value = map[string]int32{
		"ADD":     0,
		"DELETE":  1,
		"REPLACE": 2,
	}
)

func (x RouteOperation_Action) Enum() *RouteOperation_Action {
	p := new(RouteOperation_Action)
	*p = x
	return p
}

func (x RouteOperation_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteOperation_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_client_network_proto_enumTypes[0].Descriptor()
}

func (RouteOperation_Action) Type() protoreflect.EnumType {
	return &file_client_network_proto_enumTypes[0]
}

func (x RouteOperation_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteOperation_Action.Descriptor instead.
func (RouteOperation_Action) EnumDescriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{4, 0}
}

type RoutingPolicyOperation_Action int32

const (
	RoutingPolicyOperation_ADD     RoutingPolicyOperation_Action = 0
	RoutingPolicyOperation_DELETE  RoutingPolicyOperation_Action = 1
	RoutingPolicyOperation_REPLACE RoutingPolicyOperation_Action = 2
)

// Enum value maps for RoutingPolicyOperation_Action.
var (
	RoutingPolicyOperation_Action_name = map[int32]string{
		0: "ADD",
		1: "DELETE",
		2: "REPLACE",
	}
	RoutingPolicyOperation_Action_value = map[string]int32{
		"ADD":     0,
		"DELETE":  1,
		"REPLACE": 2,
	}
)

func (x RoutingPolicyOperation_Action) Enum() *RoutingPolicyOperation_Action {
	p := new(RoutingPolicyOperation_Action)
	*p = x
	return p
}

func (x RoutingPolicyOperation_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingPolicyOperation_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_client_network_proto_enumTypes[1].Descriptor()
}

func (RoutingPolicyOperation_Action) Type() protoreflect.EnumType {
	return &file_client_network_proto_enumTypes[1]
}

func (x RoutingPolicyOperation_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingPolicyOperation_Action.Descriptor instead.
func (RoutingPolicyOperation_Action) EnumDescriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{5, 0}
}

type TableOperation_Action int32

const (
	TableOperation_ADD     TableOperation_Action = 0
	TableOperation_DELETE  TableOperation_Action = 1
	TableOperation_REPLACE TableOperation_Action = 2
)

// Enum value maps for TableOperation_Action.
var (
	TableOperation_Action_name = map[int32]string{
		0: "ADD",
		1: "DELETE",
		2: "REPLACE",
	}
	TableOperation_Action_value = map[string]int32{
		"ADD":     0,
		"DELETE":  1,
		"REPLACE": 2,
	}
)

func (x TableOperation_Action) Enum() *TableOperation_Action {
	p := new(TableOperation_Action)
	*p = x
	return p
}

func (x TableOperation_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableOperation_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_client_network_proto_enumTypes[2].Descriptor()
}

func (TableOperation_Action) Type() protoreflect.EnumType {
	return &file_client_network_proto_enumTypes[2]
}

func (x TableOperation_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableOperation_Action.Descriptor instead.
func (TableOperation_Action) EnumDescriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{6, 0}
}

// Netplan YAML-based interface configuration
type NetplanConfig struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	YamlContent                  string                 `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`                                                       // Full netplan YAML content
	TestMode                     bool                   `protobuf:"varint,2,opt,name=test_mode,json=testMode,proto3" json:"test_mode,omitempty"`                                                               // Apply with test (rollback on failure)
	TestTimeoutSeconds           uint32                 `protobuf:"varint,3,opt,name=test_timeout_seconds,json=testTimeoutSeconds,proto3" json:"test_timeout_seconds,omitempty"`                               // Custom timeout in seconds (default: 10)
	PreserveControllerConnection bool                   `protobuf:"varint,4,opt,name=preserve_controller_connection,json=preserveControllerConnection,proto3" json:"preserve_controller_connection,omitempty"` // Monitor and preserve controller connection
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *NetplanConfig) Reset() {
	*x = NetplanConfig{}
	mi := &file_client_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetplanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetplanConfig) ProtoMessage() {}

func (x *NetplanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetplanConfig.ProtoReflect.Descriptor instead.
func (*NetplanConfig) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{0}
}

func (x *NetplanConfig) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

func (x *NetplanConfig) GetTestMode() bool {
	if x != nil {
		return x.TestMode
	}
	return false
}

func (x *NetplanConfig) GetTestTimeoutSeconds() uint32 {
	if x != nil {
		return x.TestTimeoutSeconds
	}
	return 0
}

func (x *NetplanConfig) GetPreserveControllerConnection() bool {
	if x != nil {
		return x.PreserveControllerConnection
	}
	return false
}

// Route management - independent from interface management
type Route struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	To        string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`                                 // Destination (e.g., "0.0.0.0/0", "10.0.0.0/24")
	Via       string                 `protobuf:"bytes,2,opt,name=via,proto3" json:"via,omitempty"`                               // Gateway IP
	Interface string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`                   // Interface name (e.g., "eth0")
	Table     uint32                 `protobuf:"varint,4,opt,name=table,proto3" json:"table,omitempty"`                          // Routing table ID (optional, default: main)
	Metric    uint32                 `protobuf:"varint,5,opt,name=metric,proto3" json:"metric,omitempty"`                        // Route metric
	Source    string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`                         // Source IP for this route
	Scope     string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`                           // Route scope (e.g., "global", "link", "host")
	IsDefault bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"` // Is this a default route
	Protocol  string                 `protobuf:"bytes,9,opt,name=protocol,proto3" json:"protocol,omitempty"`                     // Route protocol (e.g., "kernel", "static", "bgp", "ospf")
	Onlink    bool                   `protobuf:"varint,10,opt,name=onlink,proto3" json:"onlink,omitempty"`
	// Who put the route there, as the agent sees it (NetworkState.routes only):
	//
	//	"ui"      — one of this agent's 99-elchi-route-*.yaml files (the control plane's)
	//	"os"      — another netplan file (Elchi OS console/seed, cloud-init, the operator)
	//	"kernel" | "dhcp" | "bgp" | "ra" | … — the kernel's route protocol, not in any file
	//
	// "" from agents before 1.7.0.
	Owner         string `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_client_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Route) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

func (x *Route) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Route) GetTable() uint32 {
	if x != nil {
		return x.Table
	}
	return 0
}

func (x *Route) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Route) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Route) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Route) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Route) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Route) GetOnlink() bool {
	if x != nil {
		return x.Onlink
	}
	return false
}

func (x *Route) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// Policy-based routing rule - independent management
type RoutingPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`           // Source address/network
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`               // Destination address/network (optional)
	Table         uint32                 `protobuf:"varint,3,opt,name=table,proto3" json:"table,omitempty"`        // Routing table ID
	Priority      uint32                 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`  // Rule priority (lower = higher priority)
	Interface     string                 `protobuf:"bytes,5,opt,name=interface,proto3" json:"interface,omitempty"` // Interface name for netplan (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingPolicy) Reset() {
	*x = RoutingPolicy{}
	mi := &file_client_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingPolicy) ProtoMessage() {}

func (x *RoutingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingPolicy.ProtoReflect.Descriptor instead.
func (*RoutingPolicy) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{2}
}

func (x *RoutingPolicy) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RoutingPolicy) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RoutingPolicy) GetTable() uint32 {
	if x != nil {
		return x.Table
	}
	return 0
}

func (x *RoutingPolicy) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RoutingPolicy) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

// Routing table definition for system routing tables
type RoutingTableDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // Table ID (1-252, 253-255 are reserved)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Table name (e.g., "mgmt", "production")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTableDefinition) Reset() {
	*x = RoutingTableDefinition{}
	mi := &file_client_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTableDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTableDefinition) ProtoMessage() {}

func (x *RoutingTableDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTableDefinition.ProtoReflect.Descriptor instead.
func (*RoutingTableDefinition) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{3}
}

func (x *RoutingTableDefinition) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutingTableDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Route operations (add/delete/replace)
type RouteOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        RouteOperation_Action  `protobuf:"varint,1,opt,name=action,proto3,enum=client.RouteOperation_Action" json:"action,omitempty"`
	Route         *Route                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteOperation) Reset() {
	*x = RouteOperation{}
	mi := &file_client_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOperation) ProtoMessage() {}

func (x *RouteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOperation.ProtoReflect.Descriptor instead.
func (*RouteOperation) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{4}
}

func (x *RouteOperation) GetAction() RouteOperation_Action {
	if x != nil {
		return x.Action
	}
	return RouteOperation_ADD
}

func (x *RouteOperation) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

// Routing policy operations (add/delete/replace)
type RoutingPolicyOperation struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Action        RoutingPolicyOperation_Action `protobuf:"varint,1,opt,name=action,proto3,enum=client.RoutingPolicyOperation_Action" json:"action,omitempty"`
	Policy        *RoutingPolicy                `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingPolicyOperation) Reset() {
	*x = RoutingPolicyOperation{}
	mi := &file_client_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingPolicyOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingPolicyOperation) ProtoMessage() {}

func (x *RoutingPolicyOperation) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingPolicyOperation.ProtoReflect.Descriptor instead.
func (*RoutingPolicyOperation) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{5}
}

func (x *RoutingPolicyOperation) GetAction() RoutingPolicyOperation_Action {
	if x != nil {
		return x.Action
	}
	return RoutingPolicyOperation_ADD
}

func (x *RoutingPolicyOperation) GetPolicy() *RoutingPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// Routing table operations (add/delete/replace)
type TableOperation struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Action        TableOperation_Action   `protobuf:"varint,1,opt,name=action,proto3,enum=client.TableOperation_Action" json:"action,omitempty"`
	Table         *RoutingTableDefinition `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableOperation) Reset() {
	*x = TableOperation{}
	mi := &file_client_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableOperation) ProtoMessage() {}

func (x *TableOperation) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableOperation.ProtoReflect.Descriptor instead.
func (*TableOperation) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{6}
}

func (x *TableOperation) GetAction() TableOperation_Action {
	if x != nil {
		return x.Action
	}
	return TableOperation_ADD
}

func (x *TableOperation) GetTable() *RoutingTableDefinition {
	if x != nil {
		return x.Table
	}
	return nil
}

// Network state response
type NetworkState struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	Interfaces         []*InterfaceState         `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Routes             []*Route                  `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Policies           []*RoutingPolicy          `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"`
	RoutingTables      []*RoutingTableDefinition `protobuf:"bytes,4,rep,name=routing_tables,json=routingTables,proto3" json:"routing_tables,omitempty"`
	CurrentNetplanYaml string                    `protobuf:"bytes,5,opt,name=current_netplan_yaml,json=currentNetplanYaml,proto3" json:"current_netplan_yaml,omitempty"`
	// Who owns interface identity, L2 and addressing on this node:
	//
	//	"os"    — the appliance OS (Elchi OS console/seed); SUB_NETPLAN_APPLY and
	//	          SUB_NETPLAN_ROLLBACK are refused, the UI shows interfaces read-only
	//	"agent" — this agent, through netplan (a plain Linux host)
	InterfacesManagedBy string `protobuf:"bytes,6,opt,name=interfaces_managed_by,json=interfacesManagedBy,proto3" json:"interfaces_managed_by,omitempty"`
	// Interfaces the OS configured whose pinned card is not in the machine
	// (Elchi OS: the NIC was replaced or removed); they are absent from
	// `interfaces`. Empty elsewhere.
	MissingInterfaces []string `protobuf:"bytes,7,rep,name=missing_interfaces,json=missingInterfaces,proto3" json:"missing_interfaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkState) Reset() {
	*x = NetworkState{}
	mi := &file_client_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkState) ProtoMessage() {}

func (x *NetworkState) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkState.ProtoReflect.Descriptor instead.
func (*NetworkState) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkState) GetInterfaces() []*InterfaceState {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NetworkState) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NetworkState) GetPolicies() []*RoutingPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *NetworkState) GetRoutingTables() []*RoutingTableDefinition {
	if x != nil {
		return x.RoutingTables
	}
	return nil
}

func (x *NetworkState) GetCurrentNetplanYaml() string {
	if x != nil {
		return x.CurrentNetplanYaml
	}
	return ""
}

func (x *NetworkState) GetInterfacesManagedBy() string {
	if x != nil {
		return x.InterfacesManagedBy
	}
	return ""
}

func (x *NetworkState) GetMissingInterfaces() []string {
	if x != nil {
		return x.MissingInterfaces
	}
	return nil
}

// Interface state information
type InterfaceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                      // Interface name
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`                            // Assigned IP addresses
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                                    // Administrative state: "up" or "down"
	HasCarrier    bool                   `protobuf:"varint,4,opt,name=has_carrier,json=hasCarrier,proto3" json:"has_carrier,omitempty"`       // Physical link status (IFF_RUNNING)
	MacAddress    string                 `protobuf:"bytes,5,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`        // MAC address
	Mtu           uint32                 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`                                       // MTU size
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                                      // ethernet | bond | vlan | bridge | dummy | veth | tun | wireguard | other
	OperState     string                 `protobuf:"bytes,8,opt,name=oper_state,json=operState,proto3" json:"oper_state,omitempty"`           // IFLA_OPERSTATE as sysfs spells it: up | down | lowerlayerdown | dormant | notpresent | testing | unknown
	SpeedMbps     uint32                 `protobuf:"varint,9,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`          // Link speed, 0 = unknown/virtual
	PermanentMac  string                 `protobuf:"bytes,10,opt,name=permanent_mac,json=permanentMac,proto3" json:"permanent_mac,omitempty"` // Hardware MAC (IFLA_PERM_ADDRESS), "" when none
	Driver        string                 `protobuf:"bytes,11,opt,name=driver,proto3" json:"driver,omitempty"`                                 // Kernel driver name, "" for virtual devices
	Owner         string                 `protobuf:"bytes,12,opt,name=owner,proto3" json:"owner,omitempty"`                                   // os | ui | ui-legacy | service | unmanaged (see NetworkState.interfaces_managed_by)
	SourceFile    string                 `protobuf:"bytes,13,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`       // Basename of the /etc/netplan file that defines it, "" if unmanaged
	NetplanId     string                 `protobuf:"bytes,14,opt,name=netplan_id,json=netplanId,proto3" json:"netplan_id,omitempty"`          // Definition key in that file (== name unless match/set-name is used)
	Parent        string                 `protobuf:"bytes,15,opt,name=parent,proto3" json:"parent,omitempty"`                                 // VLAN link, or the bond/bridge master of a member
	Members       []string               `protobuf:"bytes,16,rep,name=members,proto3" json:"members,omitempty"`                               // Bond/bridge member names
	VlanId        uint32                 `protobuf:"varint,17,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`                  // 802.1Q id for a VLAN device
	Label         string                 `protobuf:"bytes,18,opt,name=label,proto3" json:"label,omitempty"`                                   // Operator-given role label from the OS ("management", …), "" otherwise
	Addressing    string                 `protobuf:"bytes,19,opt,name=addressing,proto3" json:"addressing,omitempty"`                         // static | dhcp | none — as the OS configured it; "" when unknown
	BondMode      string                 `protobuf:"bytes,20,opt,name=bond_mode,json=bondMode,proto3" json:"bond_mode,omitempty"`             // active-backup | lacp | … for a bond the OS configured; "" otherwise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceState) Reset() {
	*x = InterfaceState{}
	mi := &file_client_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceState) ProtoMessage() {}

func (x *InterfaceState) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceState.ProtoReflect.Descriptor instead.
func (*InterfaceState) Descriptor() ([]byte, []int) {
	return file_client_network_proto_rawDescGZIP(), []int{8}
}

func (x *InterfaceState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceState) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *InterfaceState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InterfaceState) GetHasCarrier() bool {
	if x != nil {
		return x.HasCarrier
	}
	return false
}

func (x *InterfaceState) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *InterfaceState) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *InterfaceState) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InterfaceState) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

func (x *InterfaceState) GetSpeedMbps() uint32 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

func (x *InterfaceState) GetPermanentMac() string {
	if x != nil {
		return x.PermanentMac
	}
	return ""
}

func (x *InterfaceState) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *InterfaceState) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *InterfaceState) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *InterfaceState) GetNetplanId() string {
	if x != nil {
		return x.NetplanId
	}
	return ""
}

func (x *InterfaceState) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *InterfaceState) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *InterfaceState) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *InterfaceState) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *InterfaceState) GetAddressing() string {
	if x != nil {
		return x.Addressing
	}
	return ""
}

func (x *InterfaceState) GetBondMode() string {
	if x != nil {
		return x.BondMode
	}
	return ""
}

var File_client_network_proto protoreflect.FileDescriptor

const file_client_network_proto_rawDesc = "" +
	"\n" +
	"\x14client/network.proto\x12\x06client\"\xc7\x01\n" +
	"\rNetplanConfig\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\tR\vyamlContent\x12\x1b\n" +
	"\ttest_mode\x18\x02 \x01(\bR\btestMode\x120\n" +
	"\x14test_timeout_seconds\x18\x03 \x01(\rR\x12testTimeoutSeconds\x12D\n" +
	"\x1epreserve_controller_connection\x18\x04 \x01(\bR\x1cpreserveControllerConnection\"\x8c\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x10\n" +
	"\x03via\x18\x02 \x01(\tR\x03via\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\x12\x14\n" +
	"\x05table\x18\x04 \x01(\rR\x05table\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\rR\x06metric\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\x12\x1a\n" +
	"\bprotocol\x18\t \x01(\tR\bprotocol\x12\x16\n" +
	"\x06onlink\x18\n" +
	" \x01(\bR\x06onlink\x12\x14\n" +
	"\x05owner\x18\v \x01(\tR\x05owner\"\x83\x01\n" +
	"\rRoutingPolicy\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05table\x18\x03 \x01(\rR\x05table\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\x12\x1c\n" +
	"\tinterface\x18\x05 \x01(\tR\tinterface\"<\n" +
	"\x16RoutingTableDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x98\x01\n" +
	"\x0eRouteOperation\x125\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1d.client.RouteOperation.ActionR\x06action\x12#\n" +
	"\x05route\x18\x02 \x01(\v2\r.client.RouteR\x05route\"*\n" +
	"\x06Action\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\v\n" +
	"\aREPLACE\x10\x02\"\xb2\x01\n" +
	"\x16RoutingPolicyOperation\x12=\n" +
	"\x06action\x18\x01 \x01(\x0e2%.client.RoutingPolicyOperation.ActionR\x06action\x12-\n" +
	"\x06policy\x18\x02 \x01(\v2\x15.client.RoutingPolicyR\x06policy\"*\n" +
	"\x06Action\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\v\n" +
	"\aREPLACE\x10\x02\"\xa9\x01\n" +
	"\x0eTableOperation\x125\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1d.client.TableOperation.ActionR\x06action\x124\n" +
	"\x05table\x18\x02 \x01(\v2\x1e.client.RoutingTableDefinitionR\x05table\"*\n" +
	"\x06Action\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\v\n" +
	"\aREPLACE\x10\x02\"\xfc\x02\n" +
	"\fNetworkState\x126\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x16.client.InterfaceStateR\n" +
	"interfaces\x12%\n" +
	"\x06routes\x18\x02 \x03(\v2\r.client.RouteR\x06routes\x121\n" +
	"\bpolicies\x18\x03 \x03(\v2\x15.client.RoutingPolicyR\bpolicies\x12E\n" +
	"\x0erouting_tables\x18\x04 \x03(\v2\x1e.client.RoutingTableDefinitionR\rroutingTables\x120\n" +
	"\x14current_netplan_yaml\x18\x05 \x01(\tR\x12currentNetplanYaml\x122\n" +
	"\x15interfaces_managed_by\x18\x06 \x01(\tR\x13interfacesManagedBy\x12-\n" +
	"\x12missing_interfaces\x18\a \x03(\tR\x11missingInterfaces\"\xaf\x04\n" +
	"\x0eInterfaceState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vhas_carrier\x18\x04 \x01(\bR\n" +
	"hasCarrier\x12\x1f\n" +
	"\vmac_address\x18\x05 \x01(\tR\n" +
	"macAddress\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"oper_state\x18\b \x01(\tR\toperState\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\t \x01(\rR\tspeedMbps\x12#\n" +
	"\rpermanent_mac\x18\n" +
	" \x01(\tR\fpermanentMac\x12\x16\n" +
	"\x06driver\x18\v \x01(\tR\x06driver\x12\x14\n" +
	"\x05owner\x18\f \x01(\tR\x05owner\x12\x1f\n" +
	"\vsource_file\x18\r \x01(\tR\n" +
	"sourceFile\x12\x1d\n" +
	"\n" +
	"netplan_id\x18\x0e \x01(\tR\tnetplanId\x12\x16\n" +
	"\x06parent\x18\x0f \x01(\tR\x06parent\x12\x18\n" +
	"\amembers\x18\x10 \x03(\tR\amembers\x12\x17\n" +
	"\avlan_id\x18\x11 \x01(\rR\x06vlanId\x12\x14\n" +
	"\x05label\x18\x12 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"addressing\x18\x13 \x01(\tR\n" +
	"addressing\x12\x1b\n" +
	"\tbond_mode\x18\x14 \x01(\tR\bbondModeB0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_network_proto_rawDescOnce sync.Once
	file_client_network_proto_rawDescData []byte
)

func file_client_network_proto_rawDescGZIP() []byte {
	file_client_network_proto_rawDescOnce.Do(func() {
		file_client_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_network_proto_rawDesc), len(file_client_network_proto_rawDesc)))
	})
	return file_client_network_proto_rawDescData
}

var file_client_network_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_client_network_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_client_network_proto_goTypes = []any{
	(RouteOperation_Action)(0),         // 0: client.RouteOperation.Action
	(RoutingPolicyOperation_Action)(0), // 1: client.RoutingPolicyOperation.Action
	(TableOperation_Action)(0),         // 2: client.TableOperation.Action
	(*NetplanConfig)(nil),              // 3: client.NetplanConfig
	(*Route)(nil),                      // 4: client.Route
	(*RoutingPolicy)(nil),              // 5: client.RoutingPolicy
	(*RoutingTableDefinition)(nil),     // 6: client.RoutingTableDefinition
	(*RouteOperation)(nil),             // 7: client.RouteOperation
	(*RoutingPolicyOperation)(nil),     // 8: client.RoutingPolicyOperation
	(*TableOperation)(nil),             // 9: client.TableOperation
	(*NetworkState)(nil),               // 10: client.NetworkState
	(*InterfaceState)(nil),             // 11: client.InterfaceState
}
var file_client_network_proto_depIdxs = []int32{
	0,  // 0: client.RouteOperation.action:type_name -> client.RouteOperation.Action
	4,  // 1: client.RouteOperation.route:type_name -> client.Route
	1,  // 2: client.RoutingPolicyOperation.action:type_name -> client.RoutingPolicyOperation.Action
	5,  // 3: client.RoutingPolicyOperation.policy:type_name -> client.RoutingPolicy
	2,  // 4: client.TableOperation.action:type_name -> client.TableOperation.Action
	6,  // 5: client.TableOperation.table:type_name -> client.RoutingTableDefinition
	11, // 6: client.NetworkState.interfaces:type_name -> client.InterfaceState
	4,  // 7: client.NetworkState.routes:type_name -> client.Route
	5,  // 8: client.NetworkState.policies:type_name -> client.RoutingPolicy
	6,  // 9: client.NetworkState.routing_tables:type_name -> client.RoutingTableDefinition
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_client_network_proto_init() }
func file_client_network_proto_init() {
	if File_client_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_network_proto_rawDesc), len(file_client_network_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_network_proto_goTypes,
		DependencyIndexes: file_client_network_proto_depIdxs,
		EnumInfos:         file_client_network_proto_enumTypes,
		MessageInfos:      file_client_network_proto_msgTypes,
	}.Build()
	File_client_network_proto = out.File
	file_client_network_proto_goTypes = nil
	file_client_network_proto_depIdxs = nil
}
