// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/request.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_LOG_TYPE_ALL    LogType = 0 // Both system and access logs
	LogType_LOG_TYPE_SYSTEM LogType = 1 // Only system logs (envoy internal)
	LogType_LOG_TYPE_ACCESS LogType = 2 // Only access logs (HTTP requests)
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_TYPE_ALL",
		1: "LOG_TYPE_SYSTEM",
		2: "LOG_TYPE_ACCESS",
	}
	LogType_value = map[string]int32{
		"LOG_TYPE_ALL":    0,
		"LOG_TYPE_SYSTEM": 1,
		"LOG_TYPE_ACCESS": 2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_request_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_client_request_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{0}
}

type HttpMethod int32

const (
	HttpMethod_UNSPECIFIED HttpMethod = 0
	HttpMethod_GET         HttpMethod = 1
	HttpMethod_POST        HttpMethod = 2
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "GET",
		2: "POST",
	}
	HttpMethod_value = map[string]int32{
		"UNSPECIFIED": 0,
		"GET":         1,
		"POST":        2,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_client_request_proto_enumTypes[1].Descriptor()
}

func (HttpMethod) Type() protoreflect.EnumType {
	return &file_client_request_proto_enumTypes[1]
}

func (x HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpMethod.Descriptor instead.
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{1}
}

type VersionOperation int32

const (
	VersionOperation_GET_VERSIONS VersionOperation = 0
	VersionOperation_SET_VERSION  VersionOperation = 1
)

// Enum value maps for VersionOperation.
var (
	VersionOperation_name = map[int32]string{
		0: "GET_VERSIONS",
		1: "SET_VERSION",
	}
	VersionOperation_value = map[string]int32{
		"GET_VERSIONS": 0,
		"SET_VERSION":  1,
	}
)

func (x VersionOperation) Enum() *VersionOperation {
	p := new(VersionOperation)
	*p = x
	return p
}

func (x VersionOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_client_request_proto_enumTypes[2].Descriptor()
}

func (VersionOperation) Type() protoreflect.EnumType {
	return &file_client_request_proto_enumTypes[2]
}

func (x VersionOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionOperation.Descriptor instead.
func (VersionOperation) EnumDescriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{2}
}

// Deploy related messages
type RequestDeploy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DownstreamAddress string                 `protobuf:"bytes,2,opt,name=downstream_address,json=downstreamAddress,proto3" json:"downstream_address,omitempty"`
	Port              uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Version           string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Bootstrap         []byte                 `protobuf:"bytes,5,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	InterfaceId       string                 `protobuf:"bytes,6,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	IpMode            string                 `protobuf:"bytes,7,opt,name=ip_mode,json=ipMode,proto3" json:"ip_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RequestDeploy) Reset() {
	*x = RequestDeploy{}
	mi := &file_client_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeploy) ProtoMessage() {}

func (x *RequestDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeploy.ProtoReflect.Descriptor instead.
func (*RequestDeploy) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDeploy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestDeploy) GetDownstreamAddress() string {
	if x != nil {
		return x.DownstreamAddress
	}
	return ""
}

func (x *RequestDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestDeploy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RequestDeploy) GetBootstrap() []byte {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *RequestDeploy) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

func (x *RequestDeploy) GetIpMode() string {
	if x != nil {
		return x.IpMode
	}
	return ""
}

type RequestUnDeploy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port              uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	DownstreamAddress string                 `protobuf:"bytes,3,opt,name=downstream_address,json=downstreamAddress,proto3" json:"downstream_address,omitempty"`
	InterfaceId       string                 `protobuf:"bytes,4,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	IpMode            string                 `protobuf:"bytes,5,opt,name=ip_mode,json=ipMode,proto3" json:"ip_mode,omitempty"`
	Version           string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RequestUnDeploy) Reset() {
	*x = RequestUnDeploy{}
	mi := &file_client_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUnDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUnDeploy) ProtoMessage() {}

func (x *RequestUnDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUnDeploy.ProtoReflect.Descriptor instead.
func (*RequestUnDeploy) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{1}
}

func (x *RequestUnDeploy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestUnDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestUnDeploy) GetDownstreamAddress() string {
	if x != nil {
		return x.DownstreamAddress
	}
	return ""
}

func (x *RequestUnDeploy) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

func (x *RequestUnDeploy) GetIpMode() string {
	if x != nil {
		return x.IpMode
	}
	return ""
}

func (x *RequestUnDeploy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RequestService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Levels        []string               `protobuf:"bytes,5,rep,name=levels,proto3" json:"levels,omitempty"`
	Components    []string               `protobuf:"bytes,6,rep,name=components,proto3" json:"components,omitempty"`
	LogType       LogType                `protobuf:"varint,7,opt,name=log_type,json=logType,proto3,enum=client.LogType" json:"log_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestService) Reset() {
	*x = RequestService{}
	mi := &file_client_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestService) ProtoMessage() {}

func (x *RequestService) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestService.ProtoReflect.Descriptor instead.
func (*RequestService) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{2}
}

func (x *RequestService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestService) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestService) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RequestService) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *RequestService) GetLevels() []string {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *RequestService) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *RequestService) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_LOG_TYPE_ALL
}

type RequestUpdateBootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Bootstrap     []byte                 `protobuf:"bytes,3,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdateBootstrap) Reset() {
	*x = RequestUpdateBootstrap{}
	mi := &file_client_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdateBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateBootstrap) ProtoMessage() {}

func (x *RequestUpdateBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateBootstrap.ProtoReflect.Descriptor instead.
func (*RequestUpdateBootstrap) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUpdateBootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestUpdateBootstrap) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestUpdateBootstrap) GetBootstrap() []byte {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *RequestUpdateBootstrap) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RequestUpgradeListener struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FromVersion      string                 `protobuf:"bytes,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion        string                 `protobuf:"bytes,3,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	Port             uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                                   // Admin port for systemd service management
	Graceful         bool                   `protobuf:"varint,5,opt,name=graceful,proto3" json:"graceful,omitempty"`                                           // Perform graceful upgrade with connection draining
	DrainTimeSeconds uint32                 `protobuf:"varint,6,opt,name=drain_time_seconds,json=drainTimeSeconds,proto3" json:"drain_time_seconds,omitempty"` // Time to wait for connections to drain (default: 30s)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestUpgradeListener) Reset() {
	*x = RequestUpgradeListener{}
	mi := &file_client_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpgradeListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpgradeListener) ProtoMessage() {}

func (x *RequestUpgradeListener) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpgradeListener.ProtoReflect.Descriptor instead.
func (*RequestUpgradeListener) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{4}
}

func (x *RequestUpgradeListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestUpgradeListener) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *RequestUpgradeListener) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *RequestUpgradeListener) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestUpgradeListener) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

func (x *RequestUpgradeListener) GetDrainTimeSeconds() uint32 {
	if x != nil {
		return x.DrainTimeSeconds
	}
	return 0
}

type RequestEnvoyAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Method        HttpMethod             `protobuf:"varint,3,opt,name=method,proto3,enum=client.HttpMethod" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Queries       map[string]string      `protobuf:"bytes,5,rep,name=queries,proto3" json:"queries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEnvoyAdmin) Reset() {
	*x = RequestEnvoyAdmin{}
	mi := &file_client_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnvoyAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnvoyAdmin) ProtoMessage() {}

func (x *RequestEnvoyAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnvoyAdmin.ProtoReflect.Descriptor instead.
func (*RequestEnvoyAdmin) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{5}
}

func (x *RequestEnvoyAdmin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestEnvoyAdmin) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestEnvoyAdmin) GetMethod() HttpMethod {
	if x != nil {
		return x.Method
	}
	return HttpMethod_UNSPECIFIED
}

func (x *RequestEnvoyAdmin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestEnvoyAdmin) GetQueries() map[string]string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *RequestEnvoyAdmin) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type RequestGeneralLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGeneralLog) Reset() {
	*x = RequestGeneralLog{}
	mi := &file_client_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGeneralLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGeneralLog) ProtoMessage() {}

func (x *RequestGeneralLog) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGeneralLog.ProtoReflect.Descriptor instead.
func (*RequestGeneralLog) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{6}
}

func (x *RequestGeneralLog) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RequestClientStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestClientStats) Reset() {
	*x = RequestClientStats{}
	mi := &file_client_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestClientStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestClientStats) ProtoMessage() {}

func (x *RequestClientStats) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestClientStats.ProtoReflect.Descriptor instead.
func (*RequestClientStats) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{7}
}

// Network management requests
type RequestNetwork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Netplan-based interface configuration
	NetplanConfig *NetplanConfig `protobuf:"bytes,1,opt,name=netplan_config,json=netplanConfig,proto3" json:"netplan_config,omitempty"`
	// Route management (add/delete/list)
	RouteOperations []*RouteOperation `protobuf:"bytes,2,rep,name=route_operations,json=routeOperations,proto3" json:"route_operations,omitempty"`
	// Routing policy management (add/delete/list)
	PolicyOperations []*RoutingPolicyOperation `protobuf:"bytes,3,rep,name=policy_operations,json=policyOperations,proto3" json:"policy_operations,omitempty"`
	// Routing table definitions (for initial setup/bulk update)
	RoutingTables []*RoutingTableDefinition `protobuf:"bytes,4,rep,name=routing_tables,json=routingTables,proto3" json:"routing_tables,omitempty"`
	// Routing table operations (add/delete/replace individual tables)
	TableOperations []*TableOperation `protobuf:"bytes,5,rep,name=table_operations,json=tableOperations,proto3" json:"table_operations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestNetwork) Reset() {
	*x = RequestNetwork{}
	mi := &file_client_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNetwork) ProtoMessage() {}

func (x *RequestNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNetwork.ProtoReflect.Descriptor instead.
func (*RequestNetwork) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{8}
}

func (x *RequestNetwork) GetNetplanConfig() *NetplanConfig {
	if x != nil {
		return x.NetplanConfig
	}
	return nil
}

func (x *RequestNetwork) GetRouteOperations() []*RouteOperation {
	if x != nil {
		return x.RouteOperations
	}
	return nil
}

func (x *RequestNetwork) GetPolicyOperations() []*RoutingPolicyOperation {
	if x != nil {
		return x.PolicyOperations
	}
	return nil
}

func (x *RequestNetwork) GetRoutingTables() []*RoutingTableDefinition {
	if x != nil {
		return x.RoutingTables
	}
	return nil
}

func (x *RequestNetwork) GetTableOperations() []*TableOperation {
	if x != nil {
		return x.TableOperations
	}
	return nil
}

type RequestFrr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      FrrProtocolType        `protobuf:"varint,1,opt,name=protocol,proto3,enum=client.FrrProtocolType" json:"protocol,omitempty"`
	Bgp           *RequestBgp            `protobuf:"bytes,2,opt,name=bgp,proto3" json:"bgp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFrr) Reset() {
	*x = RequestFrr{}
	mi := &file_client_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFrr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFrr) ProtoMessage() {}

func (x *RequestFrr) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFrr.ProtoReflect.Descriptor instead.
func (*RequestFrr) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{9}
}

func (x *RequestFrr) GetProtocol() FrrProtocolType {
	if x != nil {
		return x.Protocol
	}
	return FrrProtocolType_FRR_PROTOCOL_UNKNOWN
}

func (x *RequestFrr) GetBgp() *RequestBgp {
	if x != nil {
		return x.Bgp
	}
	return nil
}

type RequestEnvoyVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     VersionOperation       `protobuf:"varint,1,opt,name=operation,proto3,enum=client.VersionOperation" json:"operation,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ForceDownload bool                   `protobuf:"varint,3,opt,name=force_download,json=forceDownload,proto3" json:"force_download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEnvoyVersion) Reset() {
	*x = RequestEnvoyVersion{}
	mi := &file_client_request_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnvoyVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnvoyVersion) ProtoMessage() {}

func (x *RequestEnvoyVersion) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnvoyVersion.ProtoReflect.Descriptor instead.
func (*RequestEnvoyVersion) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{10}
}

func (x *RequestEnvoyVersion) GetOperation() VersionOperation {
	if x != nil {
		return x.Operation
	}
	return VersionOperation_GET_VERSIONS
}

func (x *RequestEnvoyVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RequestEnvoyVersion) GetForceDownload() bool {
	if x != nil {
		return x.ForceDownload
	}
	return false
}

type RequestWafVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     VersionOperation       `protobuf:"varint,1,opt,name=operation,proto3,enum=client.VersionOperation" json:"operation,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ForceDownload bool                   `protobuf:"varint,3,opt,name=force_download,json=forceDownload,proto3" json:"force_download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWafVersion) Reset() {
	*x = RequestWafVersion{}
	mi := &file_client_request_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWafVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWafVersion) ProtoMessage() {}

func (x *RequestWafVersion) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWafVersion.ProtoReflect.Descriptor instead.
func (*RequestWafVersion) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{11}
}

func (x *RequestWafVersion) GetOperation() VersionOperation {
	if x != nil {
		return x.Operation
	}
	return VersionOperation_GET_VERSIONS
}

func (x *RequestWafVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RequestWafVersion) GetForceDownload() bool {
	if x != nil {
		return x.ForceDownload
	}
	return false
}

type RequestFilebeat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Inputs              []*FilebeatInput       `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	TimestampProcessor  *TimestampProcessor    `protobuf:"bytes,2,opt,name=timestamp_processor,json=timestampProcessor,proto3" json:"timestamp_processor,omitempty"`
	DropFieldsProcessor *DropFieldsProcessor   `protobuf:"bytes,3,opt,name=drop_fields_processor,json=dropFieldsProcessor,proto3" json:"drop_fields_processor,omitempty"`
	FilebeatOutput      *FilebeatOutput        `protobuf:"bytes,4,opt,name=filebeat_output,json=filebeatOutput,proto3" json:"filebeat_output,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestFilebeat) Reset() {
	*x = RequestFilebeat{}
	mi := &file_client_request_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFilebeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFilebeat) ProtoMessage() {}

func (x *RequestFilebeat) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFilebeat.ProtoReflect.Descriptor instead.
func (*RequestFilebeat) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{12}
}

func (x *RequestFilebeat) GetInputs() []*FilebeatInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RequestFilebeat) GetTimestampProcessor() *TimestampProcessor {
	if x != nil {
		return x.TimestampProcessor
	}
	return nil
}

func (x *RequestFilebeat) GetDropFieldsProcessor() *DropFieldsProcessor {
	if x != nil {
		return x.DropFieldsProcessor
	}
	return nil
}

func (x *RequestFilebeat) GetFilebeatOutput() *FilebeatOutput {
	if x != nil {
		return x.FilebeatOutput
	}
	return nil
}

type RequestRsyslog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RsyslogConfig *RsyslogConfig         `protobuf:"bytes,1,opt,name=rsyslog_config,json=rsyslogConfig,proto3" json:"rsyslog_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRsyslog) Reset() {
	*x = RequestRsyslog{}
	mi := &file_client_request_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRsyslog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRsyslog) ProtoMessage() {}

func (x *RequestRsyslog) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRsyslog.ProtoReflect.Descriptor instead.
func (*RequestRsyslog) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{13}
}

func (x *RequestRsyslog) GetRsyslogConfig() *RsyslogConfig {
	if x != nil {
		return x.RsyslogConfig
	}
	return nil
}

// RequestShield carries an elchi-shield operation. The Command's SubCommandType
// selects the action: UPDATE_SHIELD_CONFIG uses `config`; GET_SHIELD_CONFIG and
// GET_SHIELD_STATUS carry no body.
type RequestShield struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ShieldConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestShield) Reset() {
	*x = RequestShield{}
	mi := &file_client_request_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestShield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestShield) ProtoMessage() {}

func (x *RequestShield) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestShield.ProtoReflect.Descriptor instead.
func (*RequestShield) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{14}
}

func (x *RequestShield) GetConfig() *ShieldConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_client_request_proto protoreflect.FileDescriptor

const file_client_request_proto_rawDesc = "" +
	"\n" +
	"\x14client/request.proto\x12\x06client\x1a\x14client/network.proto\x1a\x10client/frr.proto\x1a\x15client/filebeat.proto\x1a\x14client/rsyslog.proto\x1a\x13client/shield.proto\"\xda\x01\n" +
	"\rRequestDeploy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x12downstream_address\x18\x02 \x01(\tR\x11downstreamAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\tbootstrap\x18\x05 \x01(\fR\tbootstrap\x12!\n" +
	"\finterface_id\x18\x06 \x01(\tR\vinterfaceId\x12\x17\n" +
	"\aip_mode\x18\a \x01(\tR\x06ipMode\"\xbe\x01\n" +
	"\x0fRequestUnDeploy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12-\n" +
	"\x12downstream_address\x18\x03 \x01(\tR\x11downstreamAddress\x12!\n" +
	"\finterface_id\x18\x04 \x01(\tR\vinterfaceId\x12\x17\n" +
	"\aip_mode\x18\x05 \x01(\tR\x06ipMode\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\xca\x01\n" +
	"\x0eRequestService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x16\n" +
	"\x06levels\x18\x05 \x03(\tR\x06levels\x12\x1e\n" +
	"\n" +
	"components\x18\x06 \x03(\tR\n" +
	"components\x12*\n" +
	"\blog_type\x18\a \x01(\x0e2\x0f.client.LogTypeR\alogType\"x\n" +
	"\x16RequestUpdateBootstrap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1c\n" +
	"\tbootstrap\x18\x03 \x01(\fR\tbootstrap\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xcc\x01\n" +
	"\x16RequestUpgradeListener\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\tR\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x03 \x01(\tR\ttoVersion\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1a\n" +
	"\bgraceful\x18\x05 \x01(\bR\bgraceful\x12,\n" +
	"\x12drain_time_seconds\x18\x06 \x01(\rR\x10drainTimeSeconds\"\x8d\x02\n" +
	"\x11RequestEnvoyAdmin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12*\n" +
	"\x06method\x18\x03 \x01(\x0e2\x12.client.HttpMethodR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12@\n" +
	"\aqueries\x18\x05 \x03(\v2&.client.RequestEnvoyAdmin.QueriesEntryR\aqueries\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x1a:\n" +
	"\fQueriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x11RequestGeneralLog\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"\x14\n" +
	"\x12RequestClientStats\"\xe8\x02\n" +
	"\x0eRequestNetwork\x12<\n" +
	"\x0enetplan_config\x18\x01 \x01(\v2\x15.client.NetplanConfigR\rnetplanConfig\x12A\n" +
	"\x10route_operations\x18\x02 \x03(\v2\x16.client.RouteOperationR\x0frouteOperations\x12K\n" +
	"\x11policy_operations\x18\x03 \x03(\v2\x1e.client.RoutingPolicyOperationR\x10policyOperations\x12E\n" +
	"\x0erouting_tables\x18\x04 \x03(\v2\x1e.client.RoutingTableDefinitionR\rroutingTables\x12A\n" +
	"\x10table_operations\x18\x05 \x03(\v2\x16.client.TableOperationR\x0ftableOperations\"g\n" +
	"\n" +
	"RequestFrr\x123\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x17.client.FrrProtocolTypeR\bprotocol\x12$\n" +
	"\x03bgp\x18\x02 \x01(\v2\x12.client.RequestBgpR\x03bgp\"\x8e\x01\n" +
	"\x13RequestEnvoyVersion\x126\n" +
	"\toperation\x18\x01 \x01(\x0e2\x18.client.VersionOperationR\toperation\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0eforce_download\x18\x03 \x01(\bR\rforceDownload\"\x8c\x01\n" +
	"\x11RequestWafVersion\x126\n" +
	"\toperation\x18\x01 \x01(\x0e2\x18.client.VersionOperationR\toperation\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0eforce_download\x18\x03 \x01(\bR\rforceDownload\"\x9f\x02\n" +
	"\x0fRequestFilebeat\x12-\n" +
	"\x06inputs\x18\x01 \x03(\v2\x15.client.FilebeatInputR\x06inputs\x12K\n" +
	"\x13timestamp_processor\x18\x02 \x01(\v2\x1a.client.TimestampProcessorR\x12timestampProcessor\x12O\n" +
	"\x15drop_fields_processor\x18\x03 \x01(\v2\x1b.client.DropFieldsProcessorR\x13dropFieldsProcessor\x12?\n" +
	"\x0ffilebeat_output\x18\x04 \x01(\v2\x16.client.FilebeatOutputR\x0efilebeatOutput\"N\n" +
	"\x0eRequestRsyslog\x12<\n" +
	"\x0ersyslog_config\x18\x01 \x01(\v2\x15.client.RsyslogConfigR\rrsyslogConfig\"=\n" +
	"\rRequestShield\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.client.ShieldConfigR\x06config*E\n" +
	"\aLogType\x12\x10\n" +
	"\fLOG_TYPE_ALL\x10\x00\x12\x13\n" +
	"\x0fLOG_TYPE_SYSTEM\x10\x01\x12\x13\n" +
	"\x0fLOG_TYPE_ACCESS\x10\x02*0\n" +
	"\n" +
	"HttpMethod\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04POST\x10\x02*5\n" +
	"\x10VersionOperation\x12\x10\n" +
	"\fGET_VERSIONS\x10\x00\x12\x0f\n" +
	"\vSET_VERSION\x10\x01B0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_request_proto_rawDescOnce sync.Once
	file_client_request_proto_rawDescData []byte
)

func file_client_request_proto_rawDescGZIP() []byte {
	file_client_request_proto_rawDescOnce.Do(func() {
		file_client_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_request_proto_rawDesc), len(file_client_request_proto_rawDesc)))
	})
	return file_client_request_proto_rawDescData
}

var file_client_request_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_client_request_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_client_request_proto_goTypes = []any{
	(LogType)(0),                   // 0: client.LogType
	(HttpMethod)(0),                // 1: client.HttpMethod
	(VersionOperation)(0),          // 2: client.VersionOperation
	(*RequestDeploy)(nil),          // 3: client.RequestDeploy
	(*RequestUnDeploy)(nil),        // 4: client.RequestUnDeploy
	(*RequestService)(nil),         // 5: client.RequestService
	(*RequestUpdateBootstrap)(nil), // 6: client.RequestUpdateBootstrap
	(*RequestUpgradeListener)(nil), // 7: client.RequestUpgradeListener
	(*RequestEnvoyAdmin)(nil),      // 8: client.RequestEnvoyAdmin
	(*RequestGeneralLog)(nil),      // 9: client.RequestGeneralLog
	(*RequestClientStats)(nil),     // 10: client.RequestClientStats
	(*RequestNetwork)(nil),         // 11: client.RequestNetwork
	(*RequestFrr)(nil),             // 12: client.RequestFrr
	(*RequestEnvoyVersion)(nil),    // 13: client.RequestEnvoyVersion
	(*RequestWafVersion)(nil),      // 14: client.RequestWafVersion
	(*RequestFilebeat)(nil),        // 15: client.RequestFilebeat
	(*RequestRsyslog)(nil),         // 16: client.RequestRsyslog
	(*RequestShield)(nil),          // 17: client.RequestShield
	nil,                            // 18: client.RequestEnvoyAdmin.QueriesEntry
	(*NetplanConfig)(nil),          // 19: client.NetplanConfig
	(*RouteOperation)(nil),         // 20: client.RouteOperation
	(*RoutingPolicyOperation)(nil), // 21: client.RoutingPolicyOperation
	(*RoutingTableDefinition)(nil), // 22: client.RoutingTableDefinition
	(*TableOperation)(nil),         // 23: client.TableOperation
	(FrrProtocolType)(0),           // 24: client.FrrProtocolType
	(*RequestBgp)(nil),             // 25: client.RequestBgp
	(*FilebeatInput)(nil),          // 26: client.FilebeatInput
	(*TimestampProcessor)(nil),     // 27: client.TimestampProcessor
	(*DropFieldsProcessor)(nil),    // 28: client.DropFieldsProcessor
	(*FilebeatOutput)(nil),         // 29: client.FilebeatOutput
	(*RsyslogConfig)(nil),          // 30: client.RsyslogConfig
	(*ShieldConfig)(nil),           // 31: client.ShieldConfig
}
var file_client_request_proto_depIdxs = []int32{
	0,  // 0: client.RequestService.log_type:type_name -> client.LogType
	1,  // 1: client.RequestEnvoyAdmin.method:type_name -> client.HttpMethod
	18, // 2: client.RequestEnvoyAdmin.queries:type_name -> client.RequestEnvoyAdmin.QueriesEntry
	19, // 3: client.RequestNetwork.netplan_config:type_name -> client.NetplanConfig
	20, // 4: client.RequestNetwork.route_operations:type_name -> client.RouteOperation
	21, // 5: client.RequestNetwork.policy_operations:type_name -> client.RoutingPolicyOperation
	22, // 6: client.RequestNetwork.routing_tables:type_name -> client.RoutingTableDefinition
	23, // 7: client.RequestNetwork.table_operations:type_name -> client.TableOperation
	24, // 8: client.RequestFrr.protocol:type_name -> client.FrrProtocolType
	25, // 9: client.RequestFrr.bgp:type_name -> client.RequestBgp
	2,  // 10: client.RequestEnvoyVersion.operation:type_name -> client.VersionOperation
	2,  // 11: client.RequestWafVersion.operation:type_name -> client.VersionOperation
	26, // 12: client.RequestFilebeat.inputs:type_name -> client.FilebeatInput
	27, // 13: client.RequestFilebeat.timestamp_processor:type_name -> client.TimestampProcessor
	28, // 14: client.RequestFilebeat.drop_fields_processor:type_name -> client.DropFieldsProcessor
	29, // 15: client.RequestFilebeat.filebeat_output:type_name -> client.FilebeatOutput
	30, // 16: client.RequestRsyslog.rsyslog_config:type_name -> client.RsyslogConfig
	31, // 17: client.RequestShield.config:type_name -> client.ShieldConfig
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_client_request_proto_init() }
func file_client_request_proto_init() {
	if File_client_request_proto != nil {
		return
	}
	file_client_network_proto_init()
	file_client_frr_proto_init()
	file_client_filebeat_proto_init()
	file_client_rsyslog_proto_init()
	file_client_shield_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_request_proto_rawDesc), len(file_client_request_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_request_proto_goTypes,
		DependencyIndexes: file_client_request_proto_depIdxs,
		EnumInfos:         file_client_request_proto_enumTypes,
		MessageInfos:      file_client_request_proto_msgTypes,
	}.Build()
	File_client_request_proto = out.File
	file_client_request_proto_goTypes = nil
	file_client_request_proto_depIdxs = nil
}
