// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/response.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionStatus int32

const (
	VersionStatus_SUCCESS           VersionStatus = 0
	VersionStatus_DOWNLOAD_FAILED   VersionStatus = 1
	VersionStatus_EXTRACTION_FAILED VersionStatus = 2
	VersionStatus_PERMISSION_FAILED VersionStatus = 3
	VersionStatus_VERSION_NOT_FOUND VersionStatus = 4
	VersionStatus_NETWORK_ERROR     VersionStatus = 5
	VersionStatus_DIRECTORY_ERROR   VersionStatus = 6
)

// Enum value maps for VersionStatus.
var (
	VersionStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "DOWNLOAD_FAILED",
		2: "EXTRACTION_FAILED",
		3: "PERMISSION_FAILED",
		4: "VERSION_NOT_FOUND",
		5: "NETWORK_ERROR",
		6: "DIRECTORY_ERROR",
	}
	VersionStatus_value = map[string]int32{
		"SUCCESS":           0,
		"DOWNLOAD_FAILED":   1,
		"EXTRACTION_FAILED": 2,
		"PERMISSION_FAILED": 3,
		"VERSION_NOT_FOUND": 4,
		"NETWORK_ERROR":     5,
		"DIRECTORY_ERROR":   6,
	}
)

func (x VersionStatus) Enum() *VersionStatus {
	p := new(VersionStatus)
	*p = x
	return p
}

func (x VersionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_client_response_proto_enumTypes[0].Descriptor()
}

func (VersionStatus) Type() protoreflect.EnumType {
	return &file_client_response_proto_enumTypes[0]
}

func (x VersionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionStatus.Descriptor instead.
func (VersionStatus) EnumDescriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{0}
}

type ResponseDeploy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Files             string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`
	Service           string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Network           string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	DownstreamAddress string                 `protobuf:"bytes,4,opt,name=downstream_address,json=downstreamAddress,proto3" json:"downstream_address,omitempty"`
	Port              uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	InterfaceId       string                 `protobuf:"bytes,6,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	IpMode            string                 `protobuf:"bytes,7,opt,name=ip_mode,json=ipMode,proto3" json:"ip_mode,omitempty"`
	Version           string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResponseDeploy) Reset() {
	*x = ResponseDeploy{}
	mi := &file_client_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDeploy) ProtoMessage() {}

func (x *ResponseDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDeploy.ProtoReflect.Descriptor instead.
func (*ResponseDeploy) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseDeploy) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *ResponseDeploy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResponseDeploy) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ResponseDeploy) GetDownstreamAddress() string {
	if x != nil {
		return x.DownstreamAddress
	}
	return ""
}

func (x *ResponseDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ResponseDeploy) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

func (x *ResponseDeploy) GetIpMode() string {
	if x != nil {
		return x.IpMode
	}
	return ""
}

func (x *ResponseDeploy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResponseUnDeploy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Files             string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`
	Service           string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Network           string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	DownstreamAddress string                 `protobuf:"bytes,4,opt,name=downstream_address,json=downstreamAddress,proto3" json:"downstream_address,omitempty"`
	Port              uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	InterfaceId       string                 `protobuf:"bytes,6,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	IpMode            string                 `protobuf:"bytes,7,opt,name=ip_mode,json=ipMode,proto3" json:"ip_mode,omitempty"`
	Version           string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResponseUnDeploy) Reset() {
	*x = ResponseUnDeploy{}
	mi := &file_client_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUnDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUnDeploy) ProtoMessage() {}

func (x *ResponseUnDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUnDeploy.ProtoReflect.Descriptor instead.
func (*ResponseUnDeploy) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseUnDeploy) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *ResponseUnDeploy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResponseUnDeploy) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ResponseUnDeploy) GetDownstreamAddress() string {
	if x != nil {
		return x.DownstreamAddress
	}
	return ""
}

func (x *ResponseUnDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ResponseUnDeploy) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

func (x *ResponseUnDeploy) GetIpMode() string {
	if x != nil {
		return x.IpMode
	}
	return ""
}

func (x *ResponseUnDeploy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResponseUpdateBootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUpdateBootstrap) Reset() {
	*x = ResponseUpdateBootstrap{}
	mi := &file_client_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUpdateBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpdateBootstrap) ProtoMessage() {}

func (x *ResponseUpdateBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpdateBootstrap.ProtoReflect.Descriptor instead.
func (*ResponseUpdateBootstrap) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseUpdateBootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseUpgradeListener struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FromVersion           string                 `protobuf:"bytes,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion             string                 `protobuf:"bytes,3,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	Port                  uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Graceful              bool                   `protobuf:"varint,5,opt,name=graceful,proto3" json:"graceful,omitempty"`
	SystemdServiceUpdated string                 `protobuf:"bytes,6,opt,name=systemd_service_updated,json=systemdServiceUpdated,proto3" json:"systemd_service_updated,omitempty"` // Status of systemd service update
	EnvoyRestarted        string                 `protobuf:"bytes,7,opt,name=envoy_restarted,json=envoyRestarted,proto3" json:"envoy_restarted,omitempty"`                        // Status of envoy restart
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResponseUpgradeListener) Reset() {
	*x = ResponseUpgradeListener{}
	mi := &file_client_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUpgradeListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpgradeListener) ProtoMessage() {}

func (x *ResponseUpgradeListener) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpgradeListener.ProtoReflect.Descriptor instead.
func (*ResponseUpgradeListener) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseUpgradeListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseUpgradeListener) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *ResponseUpgradeListener) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *ResponseUpgradeListener) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ResponseUpgradeListener) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

func (x *ResponseUpgradeListener) GetSystemdServiceUpdated() string {
	if x != nil {
		return x.SystemdServiceUpdated
	}
	return ""
}

func (x *ResponseUpgradeListener) GetEnvoyRestarted() string {
	if x != nil {
		return x.EnvoyRestarted
	}
	return ""
}

type ResponseService struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status *ServiceStatus         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Logs   []*Logs                `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	// Set by agents that honour RequestService time range + pagination (v1.0.3).
	Total             uint32       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"` // matching entries in the range (all pages)
	RangeSupported    bool         `protobuf:"varint,5,opt,name=range_supported,json=rangeSupported,proto3" json:"range_supported,omitempty"`
	Truncated         bool         `protobuf:"varint,6,opt,name=truncated,proto3" json:"truncated,omitempty"`                                              // a scan budget stopped the scan before `since`
	ScannedFromUnixMs int64        `protobuf:"varint,7,opt,name=scanned_from_unix_ms,json=scannedFromUnixMs,proto3" json:"scanned_from_unix_ms,omitempty"` // oldest entry time the scan reached
	Buckets           []*LogBucket `protobuf:"bytes,8,rep,name=buckets,proto3" json:"buckets,omitempty"`                                                   // newest first; only when histogram_interval_ms > 0
	// The listener's live File Access Log formats for its _access.log (v1.0.4),
	// read from the proxy's config. Empty when the agent could not read them.
	AccessFormats []*AccessLogFormat `protobuf:"bytes,9,rep,name=access_formats,json=accessFormats,proto3" json:"access_formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseService) Reset() {
	*x = ResponseService{}
	mi := &file_client_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseService) ProtoMessage() {}

func (x *ResponseService) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseService.ProtoReflect.Descriptor instead.
func (*ResponseService) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseService) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ResponseService) GetLogs() []*Logs {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ResponseService) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ResponseService) GetRangeSupported() bool {
	if x != nil {
		return x.RangeSupported
	}
	return false
}

func (x *ResponseService) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ResponseService) GetScannedFromUnixMs() int64 {
	if x != nil {
		return x.ScannedFromUnixMs
	}
	return 0
}

func (x *ResponseService) GetBuckets() []*LogBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *ResponseService) GetAccessFormats() []*AccessLogFormat {
	if x != nil {
		return x.AccessFormats
	}
	return nil
}

type AccessLogFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`     // "text" | "json" | "default" (no log_format: Envoy's default)
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // the text format, or json_format as JSON
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"` // normalised fields it logs: status, method, path, duration, request_id, ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogFormat) Reset() {
	*x = AccessLogFormat{}
	mi := &file_client_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogFormat) ProtoMessage() {}

func (x *AccessLogFormat) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogFormat.ProtoReflect.Descriptor instead.
func (*AccessLogFormat) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{5}
}

func (x *AccessLogFormat) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AccessLogFormat) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AccessLogFormat) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LogBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartUnixMs   int64                  `protobuf:"varint,1,opt,name=start_unix_ms,json=startUnixMs,proto3" json:"start_unix_ms,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ByClass       map[string]uint32      `protobuf:"bytes,3,rep,name=by_class,json=byClass,proto3" json:"by_class,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // level (error, warn, info, debug) or status class (2xx ... 5xx)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBucket) Reset() {
	*x = LogBucket{}
	mi := &file_client_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBucket) ProtoMessage() {}

func (x *LogBucket) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBucket.ProtoReflect.Descriptor instead.
func (*LogBucket) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{6}
}

func (x *LogBucket) GetStartUnixMs() int64 {
	if x != nil {
		return x.StartUnixMs
	}
	return 0
}

func (x *LogBucket) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LogBucket) GetByClass() map[string]uint32 {
	if x != nil {
		return x.ByClass
	}
	return nil
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loaded        string                 `protobuf:"bytes,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Active        string                 `protobuf:"bytes,2,opt,name=active,proto3" json:"active,omitempty"`
	MainPid       string                 `protobuf:"bytes,3,opt,name=main_pid,json=mainPid,proto3" json:"main_pid,omitempty"`
	Tasks         string                 `protobuf:"bytes,4,opt,name=tasks,proto3" json:"tasks,omitempty"`
	Memory        string                 `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu           string                 `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Cgroup        []string               `protobuf:"bytes,7,rep,name=cgroup,proto3" json:"cgroup,omitempty"`
	VipState      *VipState              `protobuf:"bytes,8,opt,name=vip_state,json=vipState,proto3" json:"vip_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_client_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceStatus) GetLoaded() string {
	if x != nil {
		return x.Loaded
	}
	return ""
}

func (x *ServiceStatus) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

func (x *ServiceStatus) GetMainPid() string {
	if x != nil {
		return x.MainPid
	}
	return ""
}

func (x *ServiceStatus) GetTasks() string {
	if x != nil {
		return x.Tasks
	}
	return ""
}

func (x *ServiceStatus) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ServiceStatus) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ServiceStatus) GetCgroup() []string {
	if x != nil {
		return x.Cgroup
	}
	return nil
}

func (x *ServiceStatus) GetVipState() *VipState {
	if x != nil {
		return x.VipState
	}
	return nil
}

// VipState is a listener's VIP announcement as the agent's health loop sees
// it: whether the /32 is on the dummy interface (and so, with BGP, advertised),
// why, and the probe counters behind the decision.
type VipState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	State                string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`   // announced | withdrawn | held | n/a
	Reason               string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // what put it in this state
	Since                string                 `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`   // RFC3339
	Vip                  string                 `protobuf:"bytes,4,opt,name=vip,proto3" json:"vip,omitempty"`
	Iface                string                 `protobuf:"bytes,5,opt,name=iface,proto3" json:"iface,omitempty"`
	ConsecutiveFailures  uint32                 `protobuf:"varint,6,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	ConsecutiveSuccesses uint32                 `protobuf:"varint,7,opt,name=consecutive_successes,json=consecutiveSuccesses,proto3" json:"consecutive_successes,omitempty"`
	RestartsInWindow     uint32                 `protobuf:"varint,8,opt,name=restarts_in_window,json=restartsInWindow,proto3" json:"restarts_in_window,omitempty"`
	LastProbe            string                 `protobuf:"bytes,9,opt,name=last_probe,json=lastProbe,proto3" json:"last_probe,omitempty"` // ok | fail | unit-down | unknown
	LastProbeDetail      string                 `protobuf:"bytes,10,opt,name=last_probe_detail,json=lastProbeDetail,proto3" json:"last_probe_detail,omitempty"`
	Bgp                  bool                   `protobuf:"varint,11,opt,name=bgp,proto3" json:"bgp,omitempty"`                             // false: the box only reports, the address is never touched
	HoldUntil            string                 `protobuf:"bytes,12,opt,name=hold_until,json=holdUntil,proto3" json:"hold_until,omitempty"` // RFC3339, when held
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VipState) Reset() {
	*x = VipState{}
	mi := &file_client_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VipState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipState) ProtoMessage() {}

func (x *VipState) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipState.ProtoReflect.Descriptor instead.
func (*VipState) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{8}
}

func (x *VipState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VipState) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VipState) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *VipState) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *VipState) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *VipState) GetConsecutiveFailures() uint32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *VipState) GetConsecutiveSuccesses() uint32 {
	if x != nil {
		return x.ConsecutiveSuccesses
	}
	return 0
}

func (x *VipState) GetRestartsInWindow() uint32 {
	if x != nil {
		return x.RestartsInWindow
	}
	return 0
}

func (x *VipState) GetLastProbe() string {
	if x != nil {
		return x.LastProbe
	}
	return ""
}

func (x *VipState) GetLastProbeDetail() string {
	if x != nil {
		return x.LastProbeDetail
	}
	return ""
}

func (x *VipState) GetBgp() bool {
	if x != nil {
		return x.Bgp
	}
	return false
}

func (x *VipState) GetHoldUntil() string {
	if x != nil {
		return x.HoldUntil
	}
	return ""
}

type Logs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UnixMs        int64                  `protobuf:"varint,5,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"` // entry time (service logs, v1.0.3)
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`                // "access" | "system" (service logs, v1.0.3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logs) Reset() {
	*x = Logs{}
	mi := &file_client_response_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logs) ProtoMessage() {}

func (x *Logs) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logs.ProtoReflect.Descriptor instead.
func (*Logs) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{9}
}

func (x *Logs) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Logs) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logs) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Logs) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Logs) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

func (x *Logs) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ResponseEnvoyAdmin struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body       string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers    map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// /logging (v1.0.4): when a pending revert restores the previous levels; 0 = none.
	LoggingRevertAtUnixMs int64 `protobuf:"varint,4,opt,name=logging_revert_at_unix_ms,json=loggingRevertAtUnixMs,proto3" json:"logging_revert_at_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResponseEnvoyAdmin) Reset() {
	*x = ResponseEnvoyAdmin{}
	mi := &file_client_response_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEnvoyAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEnvoyAdmin) ProtoMessage() {}

func (x *ResponseEnvoyAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEnvoyAdmin.ProtoReflect.Descriptor instead.
func (*ResponseEnvoyAdmin) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseEnvoyAdmin) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseEnvoyAdmin) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ResponseEnvoyAdmin) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseEnvoyAdmin) GetLoggingRevertAtUnixMs() int64 {
	if x != nil {
		return x.LoggingRevertAtUnixMs
	}
	return 0
}

type GeneralLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Module        string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	File          string                 `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralLogs) Reset() {
	*x = GeneralLogs{}
	mi := &file_client_response_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralLogs) ProtoMessage() {}

func (x *GeneralLogs) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralLogs.ProtoReflect.Descriptor instead.
func (*GeneralLogs) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{11}
}

func (x *GeneralLogs) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GeneralLogs) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GeneralLogs) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *GeneralLogs) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GeneralLogs) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *GeneralLogs) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResponseGeneralLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*GeneralLogs         `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGeneralLog) Reset() {
	*x = ResponseGeneralLog{}
	mi := &file_client_response_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGeneralLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGeneralLog) ProtoMessage() {}

func (x *ResponseGeneralLog) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGeneralLog.ProtoReflect.Descriptor instead.
func (*ResponseGeneralLog) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseGeneralLog) GetLogs() []*GeneralLogs {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ResponseClientStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPUStats              `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryStats           `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk          []*DiskStats           `protobuf:"bytes,3,rep,name=disk,proto3" json:"disk,omitempty"`
	Network       *NetworkStats          `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	System        *SystemInfo            `protobuf:"bytes,5,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseClientStats) Reset() {
	*x = ResponseClientStats{}
	mi := &file_client_response_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseClientStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseClientStats) ProtoMessage() {}

func (x *ResponseClientStats) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseClientStats.ProtoReflect.Descriptor instead.
func (*ResponseClientStats) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseClientStats) GetCpu() *CPUStats {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *ResponseClientStats) GetMemory() *MemoryStats {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *ResponseClientStats) GetDisk() []*DiskStats {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *ResponseClientStats) GetNetwork() *NetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ResponseClientStats) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

type ResponseNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NetworkState  *NetworkState          `protobuf:"bytes,3,opt,name=network_state,json=networkState,proto3" json:"network_state,omitempty"`
	CurrentYaml   string                 `protobuf:"bytes,4,opt,name=current_yaml,json=currentYaml,proto3" json:"current_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseNetwork) Reset() {
	*x = ResponseNetwork{}
	mi := &file_client_response_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNetwork) ProtoMessage() {}

func (x *ResponseNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNetwork.ProtoReflect.Descriptor instead.
func (*ResponseNetwork) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{14}
}

func (x *ResponseNetwork) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseNetwork) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseNetwork) GetNetworkState() *NetworkState {
	if x != nil {
		return x.NetworkState
	}
	return nil
}

func (x *ResponseNetwork) GetCurrentYaml() string {
	if x != nil {
		return x.CurrentYaml
	}
	return ""
}

type ResponseFrr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      FrrProtocolType        `protobuf:"varint,1,opt,name=protocol,proto3,enum=client.FrrProtocolType" json:"protocol,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Bgp           *ResponseBgp           `protobuf:"bytes,4,opt,name=bgp,proto3" json:"bgp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFrr) Reset() {
	*x = ResponseFrr{}
	mi := &file_client_response_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFrr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFrr) ProtoMessage() {}

func (x *ResponseFrr) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFrr.ProtoReflect.Descriptor instead.
func (*ResponseFrr) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{15}
}

func (x *ResponseFrr) GetProtocol() FrrProtocolType {
	if x != nil {
		return x.Protocol
	}
	return FrrProtocolType_FRR_PROTOCOL_UNKNOWN
}

func (x *ResponseFrr) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseFrr) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseFrr) GetBgp() *ResponseBgp {
	if x != nil {
		return x.Bgp
	}
	return nil
}

type ResponseEnvoyVersion struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DownloadedVersions []string               `protobuf:"bytes,1,rep,name=downloaded_versions,json=downloadedVersions,proto3" json:"downloaded_versions,omitempty"`
	InstalledVersion   string                 `protobuf:"bytes,2,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	DownloadPath       string                 `protobuf:"bytes,3,opt,name=download_path,json=downloadPath,proto3" json:"download_path,omitempty"`
	Status             VersionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=client.VersionStatus" json:"status,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResponseEnvoyVersion) Reset() {
	*x = ResponseEnvoyVersion{}
	mi := &file_client_response_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEnvoyVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEnvoyVersion) ProtoMessage() {}

func (x *ResponseEnvoyVersion) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEnvoyVersion.ProtoReflect.Descriptor instead.
func (*ResponseEnvoyVersion) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{16}
}

func (x *ResponseEnvoyVersion) GetDownloadedVersions() []string {
	if x != nil {
		return x.DownloadedVersions
	}
	return nil
}

func (x *ResponseEnvoyVersion) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *ResponseEnvoyVersion) GetDownloadPath() string {
	if x != nil {
		return x.DownloadPath
	}
	return ""
}

func (x *ResponseEnvoyVersion) GetStatus() VersionStatus {
	if x != nil {
		return x.Status
	}
	return VersionStatus_SUCCESS
}

func (x *ResponseEnvoyVersion) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ResponseWafVersion struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DownloadedVersions []string               `protobuf:"bytes,1,rep,name=downloaded_versions,json=downloadedVersions,proto3" json:"downloaded_versions,omitempty"`
	InstalledVersion   string                 `protobuf:"bytes,2,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	DownloadPath       string                 `protobuf:"bytes,3,opt,name=download_path,json=downloadPath,proto3" json:"download_path,omitempty"`
	Status             VersionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=client.VersionStatus" json:"status,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResponseWafVersion) Reset() {
	*x = ResponseWafVersion{}
	mi := &file_client_response_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseWafVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWafVersion) ProtoMessage() {}

func (x *ResponseWafVersion) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseWafVersion.ProtoReflect.Descriptor instead.
func (*ResponseWafVersion) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{17}
}

func (x *ResponseWafVersion) GetDownloadedVersions() []string {
	if x != nil {
		return x.DownloadedVersions
	}
	return nil
}

func (x *ResponseWafVersion) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *ResponseWafVersion) GetDownloadPath() string {
	if x != nil {
		return x.DownloadPath
	}
	return ""
}

func (x *ResponseWafVersion) GetStatus() VersionStatus {
	if x != nil {
		return x.Status
	}
	return VersionStatus_SUCCESS
}

func (x *ResponseWafVersion) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ResponseFilebeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                 // Operation success status
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // Success message
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                      // Error message if failed
	CurrentConfig *RequestFilebeat       `protobuf:"bytes,4,opt,name=current_config,json=currentConfig,proto3" json:"current_config,omitempty"` // Current configuration (for GET)
	ServiceStatus string                 `protobuf:"bytes,5,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"` // Service status ("active", "inactive", "failed")
	Logs          []*Logs                `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`                                        // Service logs if requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFilebeat) Reset() {
	*x = ResponseFilebeat{}
	mi := &file_client_response_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFilebeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFilebeat) ProtoMessage() {}

func (x *ResponseFilebeat) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFilebeat.ProtoReflect.Descriptor instead.
func (*ResponseFilebeat) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{18}
}

func (x *ResponseFilebeat) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseFilebeat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseFilebeat) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResponseFilebeat) GetCurrentConfig() *RequestFilebeat {
	if x != nil {
		return x.CurrentConfig
	}
	return nil
}

func (x *ResponseFilebeat) GetServiceStatus() string {
	if x != nil {
		return x.ServiceStatus
	}
	return ""
}

func (x *ResponseFilebeat) GetLogs() []*Logs {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ResponseRsyslog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServiceStatus string                 `protobuf:"bytes,3,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"` // Service status: "active", "inactive", etc.
	CurrentConfig *RsyslogConfig         `protobuf:"bytes,4,opt,name=current_config,json=currentConfig,proto3" json:"current_config,omitempty"` // Current rsyslog configuration
	Logs          []*Logs                `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRsyslog) Reset() {
	*x = ResponseRsyslog{}
	mi := &file_client_response_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRsyslog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRsyslog) ProtoMessage() {}

func (x *ResponseRsyslog) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRsyslog.ProtoReflect.Descriptor instead.
func (*ResponseRsyslog) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{19}
}

func (x *ResponseRsyslog) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseRsyslog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseRsyslog) GetServiceStatus() string {
	if x != nil {
		return x.ServiceStatus
	}
	return ""
}

func (x *ResponseRsyslog) GetCurrentConfig() *RsyslogConfig {
	if x != nil {
		return x.CurrentConfig
	}
	return nil
}

func (x *ResponseRsyslog) GetLogs() []*Logs {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ResponseShield struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // operation succeeded at the client/edge
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // human-readable detail
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // error detail when success = false
	// Config version now active on the edge (echoes shield's active_config_version /
	// /configz), so the controller can confirm the edge converged on the push.
	AppliedVersion string `protobuf:"bytes,4,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	// reload_ok reports shield's reaction to a config push: true = shield loaded the
	// new bundle cleanly; false = shield REJECTED it (invalid config) and kept its
	// last-good config — traffic is unaffected but the push did not take effect.
	// The controller should treat reload_ok = false as a failed rollout, not an outage.
	ReloadOk bool `protobuf:"varint,5,opt,name=reload_ok,json=reloadOk,proto3" json:"reload_ok,omitempty"`
	// GET_SHIELD_CONFIG: the file set currently on disk (path + sha256 + mode;
	// content is omitted for large files). Empty for status/update.
	CurrentFiles []*ShieldFile `protobuf:"bytes,6,rep,name=current_files,json=currentFiles,proto3" json:"current_files,omitempty"`
	// GET_SHIELD_STATUS: shield service state ("active"/"inactive"/"failed") and
	// recent logs, mirroring the filebeat/rsyslog status responses.
	ServiceStatus string  `protobuf:"bytes,7,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	Logs          []*Logs `protobuf:"bytes,8,rep,name=logs,proto3" json:"logs,omitempty"`
	// Further facts about the edge's shield for the status panel, as key/value
	// pairs (e.g. "shield_version", "crs_version", "engines"): new facts need no
	// proto change. The keys are the reporter's; the control plane shows what it
	// does not recognise.
	Info          map[string]string `protobuf:"bytes,9,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseShield) Reset() {
	*x = ResponseShield{}
	mi := &file_client_response_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseShield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseShield) ProtoMessage() {}

func (x *ResponseShield) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseShield.ProtoReflect.Descriptor instead.
func (*ResponseShield) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{20}
}

func (x *ResponseShield) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseShield) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseShield) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResponseShield) GetAppliedVersion() string {
	if x != nil {
		return x.AppliedVersion
	}
	return ""
}

func (x *ResponseShield) GetReloadOk() bool {
	if x != nil {
		return x.ReloadOk
	}
	return false
}

func (x *ResponseShield) GetCurrentFiles() []*ShieldFile {
	if x != nil {
		return x.CurrentFiles
	}
	return nil
}

func (x *ResponseShield) GetServiceStatus() string {
	if x != nil {
		return x.ServiceStatus
	}
	return ""
}

func (x *ResponseShield) GetLogs() []*Logs {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ResponseShield) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

type ResponseAIGateway struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // operation succeeded at the client/edge
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // human-readable detail
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // error detail when success = false
	// Bundle version now active on the edge, so the controller can confirm the
	// edge converged on the push.
	AppliedVersion string `protobuf:"bytes,4,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	// The supervisor's verdict on a push: true = the ext_proc binary accepted
	// the rendered config; false = it was rejected and the last-good config
	// stays (a failed rollout, not an outage).
	ReloadOk bool `protobuf:"varint,5,opt,name=reload_ok,json=reloadOk,proto3" json:"reload_ok,omitempty"`
	// GET_AI_GATEWAY_CONFIG: the file set currently on disk (path + sha256 +
	// mode; content omitted for large files). Empty for status/update.
	CurrentFiles []*AIGatewayFile `protobuf:"bytes,6,rep,name=current_files,json=currentFiles,proto3" json:"current_files,omitempty"`
	// GET_AI_GATEWAY_STATUS: service state ("active"/"inactive"/"failed") and
	// recent logs, mirroring the shield status response.
	ServiceStatus string  `protobuf:"bytes,7,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	Logs          []*Logs `protobuf:"bytes,8,rep,name=logs,proto3" json:"logs,omitempty"`
	// The wrapped ext_proc binary's version. Its config version gate fails
	// silently (a log line only); this lets the control plane explain a
	// reload_ok = false.
	ExtprocVersion string `protobuf:"bytes,9,opt,name=extproc_version,json=extprocVersion,proto3" json:"extproc_version,omitempty"`
	// Further facts the supervisor reports for the status panel, as key/value
	// pairs (e.g. "supervisor_version", "usage_export": "ok|failing: …",
	// "provider.<name>": "ok|…"): new facts need no proto change. The keys are
	// the supervisor's; the control plane shows what it does not recognise.
	Info          map[string]string `protobuf:"bytes,10,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAIGateway) Reset() {
	*x = ResponseAIGateway{}
	mi := &file_client_response_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAIGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAIGateway) ProtoMessage() {}

func (x *ResponseAIGateway) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAIGateway.ProtoReflect.Descriptor instead.
func (*ResponseAIGateway) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{21}
}

func (x *ResponseAIGateway) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseAIGateway) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseAIGateway) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResponseAIGateway) GetAppliedVersion() string {
	if x != nil {
		return x.AppliedVersion
	}
	return ""
}

func (x *ResponseAIGateway) GetReloadOk() bool {
	if x != nil {
		return x.ReloadOk
	}
	return false
}

func (x *ResponseAIGateway) GetCurrentFiles() []*AIGatewayFile {
	if x != nil {
		return x.CurrentFiles
	}
	return nil
}

func (x *ResponseAIGateway) GetServiceStatus() string {
	if x != nil {
		return x.ServiceStatus
	}
	return ""
}

func (x *ResponseAIGateway) GetLogs() []*Logs {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ResponseAIGateway) GetExtprocVersion() string {
	if x != nil {
		return x.ExtprocVersion
	}
	return ""
}

func (x *ResponseAIGateway) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

type ResponseAppliance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"` // false on a host that is not Elchi OS 0.5.0+
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        *ApplianceStatus       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`     // GET_APPLIANCE_STATUS
	Artifact      *ApplianceArtifact     `protobuf:"bytes,4,opt,name=artifact,proto3" json:"artifact,omitempty"` // CREATE / GET / DELETE
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`         // FETCH
	Offset        uint64                 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`    // FETCH: where `data` starts
	Eof           bool                   `protobuf:"varint,7,opt,name=eof,proto3" json:"eof,omitempty"`          // FETCH: `data` ends the file
	Info          map[string]string      `protobuf:"bytes,8,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAppliance) Reset() {
	*x = ResponseAppliance{}
	mi := &file_client_response_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAppliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAppliance) ProtoMessage() {}

func (x *ResponseAppliance) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAppliance.ProtoReflect.Descriptor instead.
func (*ResponseAppliance) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{22}
}

func (x *ResponseAppliance) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *ResponseAppliance) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseAppliance) GetStatus() *ApplianceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ResponseAppliance) GetArtifact() *ApplianceArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ResponseAppliance) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseAppliance) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ResponseAppliance) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *ResponseAppliance) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_client_response_proto protoreflect.FileDescriptor

const file_client_response_proto_rawDesc = "" +
	"\n" +
	"\x15client/response.proto\x12\x06client\x1a\x12client/stats.proto\x1a\x14client/network.proto\x1a\x10client/frr.proto\x1a\x14client/request.proto\x1a\x14client/rsyslog.proto\x1a\x13client/shield.proto\x1a\x17client/ai_gateway.proto\x1a\x16client/appliance.proto\"\xf3\x01\n" +
	"\x0eResponseDeploy\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12-\n" +
	"\x12downstream_address\x18\x04 \x01(\tR\x11downstreamAddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12!\n" +
	"\finterface_id\x18\x06 \x01(\tR\vinterfaceId\x12\x17\n" +
	"\aip_mode\x18\a \x01(\tR\x06ipMode\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\"\xf5\x01\n" +
	"\x10ResponseUnDeploy\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12-\n" +
	"\x12downstream_address\x18\x04 \x01(\tR\x11downstreamAddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12!\n" +
	"\finterface_id\x18\x06 \x01(\tR\vinterfaceId\x12\x17\n" +
	"\aip_mode\x18\a \x01(\tR\x06ipMode\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\"-\n" +
	"\x17ResponseUpdateBootstrap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x80\x02\n" +
	"\x17ResponseUpgradeListener\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\tR\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x03 \x01(\tR\ttoVersion\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1a\n" +
	"\bgraceful\x18\x05 \x01(\bR\bgraceful\x126\n" +
	"\x17systemd_service_updated\x18\x06 \x01(\tR\x15systemdServiceUpdated\x12'\n" +
	"\x0fenvoy_restarted\x18\a \x01(\tR\x0eenvoyRestarted\"\xf1\x02\n" +
	"\x0fResponseService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x15.client.ServiceStatusR\x06status\x12 \n" +
	"\x04logs\x18\x03 \x03(\v2\f.client.LogsR\x04logs\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\x12'\n" +
	"\x0frange_supported\x18\x05 \x01(\bR\x0erangeSupported\x12\x1c\n" +
	"\ttruncated\x18\x06 \x01(\bR\ttruncated\x12/\n" +
	"\x14scanned_from_unix_ms\x18\a \x01(\x03R\x11scannedFromUnixMs\x12+\n" +
	"\abuckets\x18\b \x03(\v2\x11.client.LogBucketR\abuckets\x12>\n" +
	"\x0eaccess_formats\x18\t \x03(\v2\x17.client.AccessLogFormatR\raccessFormats\"U\n" +
	"\x0fAccessLogFormat\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"\xbc\x01\n" +
	"\tLogBucket\x12\"\n" +
	"\rstart_unix_ms\x18\x01 \x01(\x03R\vstartUnixMs\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x129\n" +
	"\bby_class\x18\x03 \x03(\v2\x1e.client.LogBucket.ByClassEntryR\abyClass\x1a:\n" +
	"\fByClassEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xe1\x01\n" +
	"\rServiceStatus\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\tR\x06loaded\x12\x16\n" +
	"\x06active\x18\x02 \x01(\tR\x06active\x12\x19\n" +
	"\bmain_pid\x18\x03 \x01(\tR\amainPid\x12\x14\n" +
	"\x05tasks\x18\x04 \x01(\tR\x05tasks\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\tR\x06memory\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06cgroup\x18\a \x03(\tR\x06cgroup\x12-\n" +
	"\tvip_state\x18\b \x01(\v2\x10.client.VipStateR\bvipState\"\x88\x03\n" +
	"\bVipState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05since\x18\x03 \x01(\tR\x05since\x12\x10\n" +
	"\x03vip\x18\x04 \x01(\tR\x03vip\x12\x14\n" +
	"\x05iface\x18\x05 \x01(\tR\x05iface\x121\n" +
	"\x14consecutive_failures\x18\x06 \x01(\rR\x13consecutiveFailures\x123\n" +
	"\x15consecutive_successes\x18\a \x01(\rR\x14consecutiveSuccesses\x12,\n" +
	"\x12restarts_in_window\x18\b \x01(\rR\x10restartsInWindow\x12\x1d\n" +
	"\n" +
	"last_probe\x18\t \x01(\tR\tlastProbe\x12*\n" +
	"\x11last_probe_detail\x18\n" +
	" \x01(\tR\x0flastProbeDetail\x12\x10\n" +
	"\x03bgp\x18\v \x01(\bR\x03bgp\x12\x1d\n" +
	"\n" +
	"hold_until\x18\f \x01(\tR\tholdUntil\"\xa3\x01\n" +
	"\x04Logs\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x17\n" +
	"\aunix_ms\x18\x05 \x01(\x03R\x06unixMs\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\x82\x02\n" +
	"\x12ResponseEnvoyAdmin\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.client.ResponseEnvoyAdmin.HeadersEntryR\aheaders\x128\n" +
	"\x19logging_revert_at_unix_ms\x18\x04 \x01(\x03R\x15loggingRevertAtUnixMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\vGeneralLogs\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04file\x18\x05 \x01(\tR\x04file\x12=\n" +
	"\bmetadata\x18\x06 \x03(\v2!.client.GeneralLogs.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x12ResponseGeneralLog\x12'\n" +
	"\x04logs\x18\x01 \x03(\v2\x13.client.GeneralLogsR\x04logs\"\xe9\x01\n" +
	"\x13ResponseClientStats\x12\"\n" +
	"\x03cpu\x18\x01 \x01(\v2\x10.client.CPUStatsR\x03cpu\x12+\n" +
	"\x06memory\x18\x02 \x01(\v2\x13.client.MemoryStatsR\x06memory\x12%\n" +
	"\x04disk\x18\x03 \x03(\v2\x11.client.DiskStatsR\x04disk\x12.\n" +
	"\anetwork\x18\x04 \x01(\v2\x14.client.NetworkStatsR\anetwork\x12*\n" +
	"\x06system\x18\x05 \x01(\v2\x12.client.SystemInfoR\x06system\"\xa3\x01\n" +
	"\x0fResponseNetwork\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\rnetwork_state\x18\x03 \x01(\v2\x14.client.NetworkStateR\fnetworkState\x12!\n" +
	"\fcurrent_yaml\x18\x04 \x01(\tR\vcurrentYaml\"\x9d\x01\n" +
	"\vResponseFrr\x123\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x17.client.FrrProtocolTypeR\bprotocol\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x03bgp\x18\x04 \x01(\v2\x13.client.ResponseBgpR\x03bgp\"\xed\x01\n" +
	"\x14ResponseEnvoyVersion\x12/\n" +
	"\x13downloaded_versions\x18\x01 \x03(\tR\x12downloadedVersions\x12+\n" +
	"\x11installed_version\x18\x02 \x01(\tR\x10installedVersion\x12#\n" +
	"\rdownload_path\x18\x03 \x01(\tR\fdownloadPath\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.client.VersionStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xeb\x01\n" +
	"\x12ResponseWafVersion\x12/\n" +
	"\x13downloaded_versions\x18\x01 \x03(\tR\x12downloadedVersions\x12+\n" +
	"\x11installed_version\x18\x02 \x01(\tR\x10installedVersion\x12#\n" +
	"\rdownload_path\x18\x03 \x01(\tR\fdownloadPath\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.client.VersionStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xe5\x01\n" +
	"\x10ResponseFilebeat\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12>\n" +
	"\x0ecurrent_config\x18\x04 \x01(\v2\x17.client.RequestFilebeatR\rcurrentConfig\x12%\n" +
	"\x0eservice_status\x18\x05 \x01(\tR\rserviceStatus\x12 \n" +
	"\x04logs\x18\x06 \x03(\v2\f.client.LogsR\x04logs\"\xcc\x01\n" +
	"\x0fResponseRsyslog\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eservice_status\x18\x03 \x01(\tR\rserviceStatus\x12<\n" +
	"\x0ecurrent_config\x18\x04 \x01(\v2\x15.client.RsyslogConfigR\rcurrentConfig\x12 \n" +
	"\x04logs\x18\x05 \x03(\v2\f.client.LogsR\x04logs\"\x91\x03\n" +
	"\x0eResponseShield\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12'\n" +
	"\x0fapplied_version\x18\x04 \x01(\tR\x0eappliedVersion\x12\x1b\n" +
	"\treload_ok\x18\x05 \x01(\bR\breloadOk\x127\n" +
	"\rcurrent_files\x18\x06 \x03(\v2\x12.client.ShieldFileR\fcurrentFiles\x12%\n" +
	"\x0eservice_status\x18\a \x01(\tR\rserviceStatus\x12 \n" +
	"\x04logs\x18\b \x03(\v2\f.client.LogsR\x04logs\x124\n" +
	"\x04info\x18\t \x03(\v2 .client.ResponseShield.InfoEntryR\x04info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x03\n" +
	"\x11ResponseAIGateway\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12'\n" +
	"\x0fapplied_version\x18\x04 \x01(\tR\x0eappliedVersion\x12\x1b\n" +
	"\treload_ok\x18\x05 \x01(\bR\breloadOk\x12:\n" +
	"\rcurrent_files\x18\x06 \x03(\v2\x15.client.AIGatewayFileR\fcurrentFiles\x12%\n" +
	"\x0eservice_status\x18\a \x01(\tR\rserviceStatus\x12 \n" +
	"\x04logs\x18\b \x03(\v2\f.client.LogsR\x04logs\x12'\n" +
	"\x0fextproc_version\x18\t \x01(\tR\x0eextprocVersion\x127\n" +
	"\x04info\x18\n" +
	" \x03(\v2#.client.ResponseAIGateway.InfoEntryR\x04info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\x11ResponseAppliance\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x17.client.ApplianceStatusR\x06status\x125\n" +
	"\bartifact\x18\x04 \x01(\v2\x19.client.ApplianceArtifactR\bartifact\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x04R\x06offset\x12\x10\n" +
	"\x03eof\x18\a \x01(\bR\x03eof\x127\n" +
	"\x04info\x18\b \x03(\v2#.client.ResponseAppliance.InfoEntryR\x04info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x9e\x01\n" +
	"\rVersionStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x13\n" +
	"\x0fDOWNLOAD_FAILED\x10\x01\x12\x15\n" +
	"\x11EXTRACTION_FAILED\x10\x02\x12\x15\n" +
	"\x11PERMISSION_FAILED\x10\x03\x12\x15\n" +
	"\x11VERSION_NOT_FOUND\x10\x04\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x05\x12\x13\n" +
	"\x0fDIRECTORY_ERROR\x10\x06B0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_response_proto_rawDescOnce sync.Once
	file_client_response_proto_rawDescData []byte
)

func file_client_response_proto_rawDescGZIP() []byte {
	file_client_response_proto_rawDescOnce.Do(func() {
		file_client_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_response_proto_rawDesc), len(file_client_response_proto_rawDesc)))
	})
	return file_client_response_proto_rawDescData
}

var file_client_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_response_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_client_response_proto_goTypes = []any{
	(VersionStatus)(0),              // 0: client.VersionStatus
	(*ResponseDeploy)(nil),          // 1: client.ResponseDeploy
	(*ResponseUnDeploy)(nil),        // 2: client.ResponseUnDeploy
	(*ResponseUpdateBootstrap)(nil), // 3: client.ResponseUpdateBootstrap
	(*ResponseUpgradeListener)(nil), // 4: client.ResponseUpgradeListener
	(*ResponseService)(nil),         // 5: client.ResponseService
	(*AccessLogFormat)(nil),         // 6: client.AccessLogFormat
	(*LogBucket)(nil),               // 7: client.LogBucket
	(*ServiceStatus)(nil),           // 8: client.ServiceStatus
	(*VipState)(nil),                // 9: client.VipState
	(*Logs)(nil),                    // 10: client.Logs
	(*ResponseEnvoyAdmin)(nil),      // 11: client.ResponseEnvoyAdmin
	(*GeneralLogs)(nil),             // 12: client.GeneralLogs
	(*ResponseGeneralLog)(nil),      // 13: client.ResponseGeneralLog
	(*ResponseClientStats)(nil),     // 14: client.ResponseClientStats
	(*ResponseNetwork)(nil),         // 15: client.ResponseNetwork
	(*ResponseFrr)(nil),             // 16: client.ResponseFrr
	(*ResponseEnvoyVersion)(nil),    // 17: client.ResponseEnvoyVersion
	(*ResponseWafVersion)(nil),      // 18: client.ResponseWafVersion
	(*ResponseFilebeat)(nil),        // 19: client.ResponseFilebeat
	(*ResponseRsyslog)(nil),         // 20: client.ResponseRsyslog
	(*ResponseShield)(nil),          // 21: client.ResponseShield
	(*ResponseAIGateway)(nil),       // 22: client.ResponseAIGateway
	(*ResponseAppliance)(nil),       // 23: client.ResponseAppliance
	nil,                             // 24: client.LogBucket.ByClassEntry
	nil,                             // 25: client.ResponseEnvoyAdmin.HeadersEntry
	nil,                             // 26: client.GeneralLogs.MetadataEntry
	nil,                             // 27: client.ResponseShield.InfoEntry
	nil,                             // 28: client.ResponseAIGateway.InfoEntry
	nil,                             // 29: client.ResponseAppliance.InfoEntry
	(*CPUStats)(nil),                // 30: client.CPUStats
	(*MemoryStats)(nil),             // 31: client.MemoryStats
	(*DiskStats)(nil),               // 32: client.DiskStats
	(*NetworkStats)(nil),            // 33: client.NetworkStats
	(*SystemInfo)(nil),              // 34: client.SystemInfo
	(*NetworkState)(nil),            // 35: client.NetworkState
	(FrrProtocolType)(0),            // 36: client.FrrProtocolType
	(*ResponseBgp)(nil),             // 37: client.ResponseBgp
	(*RequestFilebeat)(nil),         // 38: client.RequestFilebeat
	(*RsyslogConfig)(nil),           // 39: client.RsyslogConfig
	(*ShieldFile)(nil),              // 40: client.ShieldFile
	(*AIGatewayFile)(nil),           // 41: client.AIGatewayFile
	(*ApplianceStatus)(nil),         // 42: client.ApplianceStatus
	(*ApplianceArtifact)(nil),       // 43: client.ApplianceArtifact
}
var file_client_response_proto_depIdxs = []int32{
	8,  // 0: client.ResponseService.status:type_name -> client.ServiceStatus
	10, // 1: client.ResponseService.logs:type_name -> client.Logs
	7,  // 2: client.ResponseService.buckets:type_name -> client.LogBucket
	6,  // 3: client.ResponseService.access_formats:type_name -> client.AccessLogFormat
	24, // 4: client.LogBucket.by_class:type_name -> client.LogBucket.ByClassEntry
	9,  // 5: client.ServiceStatus.vip_state:type_name -> client.VipState
	25, // 6: client.ResponseEnvoyAdmin.headers:type_name -> client.ResponseEnvoyAdmin.HeadersEntry
	26, // 7: client.GeneralLogs.metadata:type_name -> client.GeneralLogs.MetadataEntry
	12, // 8: client.ResponseGeneralLog.logs:type_name -> client.GeneralLogs
	30, // 9: client.ResponseClientStats.cpu:type_name -> client.CPUStats
	31, // 10: client.ResponseClientStats.memory:type_name -> client.MemoryStats
	32, // 11: client.ResponseClientStats.disk:type_name -> client.DiskStats
	33, // 12: client.ResponseClientStats.network:type_name -> client.NetworkStats
	34, // 13: client.ResponseClientStats.system:type_name -> client.SystemInfo
	35, // 14: client.ResponseNetwork.network_state:type_name -> client.NetworkState
	36, // 15: client.ResponseFrr.protocol:type_name -> client.FrrProtocolType
	37, // 16: client.ResponseFrr.bgp:type_name -> client.ResponseBgp
	0,  // 17: client.ResponseEnvoyVersion.status:type_name -> client.VersionStatus
	0,  // 18: client.ResponseWafVersion.status:type_name -> client.VersionStatus
	38, // 19: client.ResponseFilebeat.current_config:type_name -> client.RequestFilebeat
	10, // 20: client.ResponseFilebeat.logs:type_name -> client.Logs
	39, // 21: client.ResponseRsyslog.current_config:type_name -> client.RsyslogConfig
	10, // 22: client.ResponseRsyslog.logs:type_name -> client.Logs
	40, // 23: client.ResponseShield.current_files:type_name -> client.ShieldFile
	10, // 24: client.ResponseShield.logs:type_name -> client.Logs
	27, // 25: client.ResponseShield.info:type_name -> client.ResponseShield.InfoEntry
	41, // 26: client.ResponseAIGateway.current_files:type_name -> client.AIGatewayFile
	10, // 27: client.ResponseAIGateway.logs:type_name -> client.Logs
	28, // 28: client.ResponseAIGateway.info:type_name -> client.ResponseAIGateway.InfoEntry
	42, // 29: client.ResponseAppliance.status:type_name -> client.ApplianceStatus
	43, // 30: client.ResponseAppliance.artifact:type_name -> client.ApplianceArtifact
	29, // 31: client.ResponseAppliance.info:type_name -> client.ResponseAppliance.InfoEntry
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_client_response_proto_init() }
func file_client_response_proto_init() {
	if File_client_response_proto != nil {
		return
	}
	file_client_stats_proto_init()
	file_client_network_proto_init()
	file_client_frr_proto_init()
	file_client_request_proto_init()
	file_client_rsyslog_proto_init()
	file_client_shield_proto_init()
	file_client_ai_gateway_proto_init()
	file_client_appliance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_response_proto_rawDesc), len(file_client_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_response_proto_goTypes,
		DependencyIndexes: file_client_response_proto_depIdxs,
		EnumInfos:         file_client_response_proto_enumTypes,
		MessageInfos:      file_client_response_proto_msgTypes,
	}.Build()
	File_client_response_proto = out.File
	file_client_response_proto_goTypes = nil
	file_client_response_proto_depIdxs = nil
}
