// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/rsyslog.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rsyslog configuration structure
type RsyslogConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RsyslogOutput *RsyslogOutput         `protobuf:"bytes,1,opt,name=rsyslog_output,json=rsyslogOutput,proto3" json:"rsyslog_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsyslogConfig) Reset() {
	*x = RsyslogConfig{}
	mi := &file_client_rsyslog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsyslogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyslogConfig) ProtoMessage() {}

func (x *RsyslogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_client_rsyslog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyslogConfig.ProtoReflect.Descriptor instead.
func (*RsyslogConfig) Descriptor() ([]byte, []int) {
	return file_client_rsyslog_proto_rawDescGZIP(), []int{0}
}

func (x *RsyslogConfig) GetRsyslogOutput() *RsyslogOutput {
	if x != nil {
		return x.RsyslogOutput
	}
	return nil
}

// Rsyslog output configuration (only variable fields)
type RsyslogOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`     // Remote syslog server address (e.g., "syslog.example.com")
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`        // Remote syslog port (e.g., 514)
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // Protocol: "udp" or "tcp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsyslogOutput) Reset() {
	*x = RsyslogOutput{}
	mi := &file_client_rsyslog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsyslogOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyslogOutput) ProtoMessage() {}

func (x *RsyslogOutput) ProtoReflect() protoreflect.Message {
	mi := &file_client_rsyslog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyslogOutput.ProtoReflect.Descriptor instead.
func (*RsyslogOutput) Descriptor() ([]byte, []int) {
	return file_client_rsyslog_proto_rawDescGZIP(), []int{1}
}

func (x *RsyslogOutput) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RsyslogOutput) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RsyslogOutput) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

var File_client_rsyslog_proto protoreflect.FileDescriptor

const file_client_rsyslog_proto_rawDesc = "" +
	"\n" +
	"\x14client/rsyslog.proto\x12\x06client\"M\n" +
	"\rRsyslogConfig\x12<\n" +
	"\x0ersyslog_output\x18\x01 \x01(\v2\x15.client.RsyslogOutputR\rrsyslogOutput\"W\n" +
	"\rRsyslogOutput\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocolB0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_rsyslog_proto_rawDescOnce sync.Once
	file_client_rsyslog_proto_rawDescData []byte
)

func file_client_rsyslog_proto_rawDescGZIP() []byte {
	file_client_rsyslog_proto_rawDescOnce.Do(func() {
		file_client_rsyslog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_rsyslog_proto_rawDesc), len(file_client_rsyslog_proto_rawDesc)))
	})
	return file_client_rsyslog_proto_rawDescData
}

var file_client_rsyslog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_rsyslog_proto_goTypes = []any{
	(*RsyslogConfig)(nil), // 0: client.RsyslogConfig
	(*RsyslogOutput)(nil), // 1: client.RsyslogOutput
}
var file_client_rsyslog_proto_depIdxs = []int32{
	1, // 0: client.RsyslogConfig.rsyslog_output:type_name -> client.RsyslogOutput
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_rsyslog_proto_init() }
func file_client_rsyslog_proto_init() {
	if File_client_rsyslog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_rsyslog_proto_rawDesc), len(file_client_rsyslog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_rsyslog_proto_goTypes,
		DependencyIndexes: file_client_rsyslog_proto_depIdxs,
		MessageInfos:      file_client_rsyslog_proto_msgTypes,
	}.Build()
	File_client_rsyslog_proto = out.File
	file_client_rsyslog_proto_goTypes = nil
	file_client_rsyslog_proto_depIdxs = nil
}
