// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/shield.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShieldFile is one file in shield's managed config directory.
type ShieldFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path RELATIVE to shield's managed config root, e.g. "api-public.yaml" or
	// "feeds/spamhaus_drop.json". The client MUST reject absolute paths and any ".."
	// segment (path-traversal guard) and only write under the managed root.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Content source. Small text/config files are pushed inline; large binary
	// artifacts (GeoIP .mmdb, big feeds) are fetched by the client itself to avoid
	// bloating the command stream (mirrors the envoy/waf version-download pattern).
	//
	// Types that are valid to be assigned to Source:
	//
	//	*ShieldFile_Inline
	//	*ShieldFile_Download
	Source isShieldFile_Source `protobuf_oneof:"source"`
	// Lowercase-hex sha256 of the final file content. Used for idempotent writes
	// (skip rewrite when unchanged) and integrity verification. Required.
	Sha256 string `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Octal file mode, e.g. "0600". Empty = client default (0600). Secret-bearing
	// files (PEM keys, JWK Sets) should be 0600.
	Mode          string `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShieldFile) Reset() {
	*x = ShieldFile{}
	mi := &file_client_shield_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldFile) ProtoMessage() {}

func (x *ShieldFile) ProtoReflect() protoreflect.Message {
	mi := &file_client_shield_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldFile.ProtoReflect.Descriptor instead.
func (*ShieldFile) Descriptor() ([]byte, []int) {
	return file_client_shield_proto_rawDescGZIP(), []int{0}
}

func (x *ShieldFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShieldFile) GetSource() isShieldFile_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ShieldFile) GetInline() []byte {
	if x != nil {
		if x, ok := x.Source.(*ShieldFile_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

func (x *ShieldFile) GetDownload() *ShieldDownload {
	if x != nil {
		if x, ok := x.Source.(*ShieldFile_Download); ok {
			return x.Download
		}
	}
	return nil
}

func (x *ShieldFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ShieldFile) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type isShieldFile_Source interface {
	isShieldFile_Source()
}

type ShieldFile_Inline struct {
	Inline []byte `protobuf:"bytes,2,opt,name=inline,proto3,oneof"` // raw file bytes (YAML/JSON/PEM/small feed)
}

type ShieldFile_Download struct {
	Download *ShieldDownload `protobuf:"bytes,3,opt,name=download,proto3,oneof"` // client downloads the artifact (large files)
}

func (*ShieldFile_Inline) isShieldFile_Source() {}

func (*ShieldFile_Download) isShieldFile_Source() {}

// ShieldDownload references a large artifact the client fetches itself instead of
// receiving it inline (e.g. a GeoIP MaxMind .mmdb from the elchi-archive mirror).
type ShieldDownload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`         // artifact URL
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // artifact version/tag, for tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShieldDownload) Reset() {
	*x = ShieldDownload{}
	mi := &file_client_shield_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldDownload) ProtoMessage() {}

func (x *ShieldDownload) ProtoReflect() protoreflect.Message {
	mi := &file_client_shield_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldDownload.ProtoReflect.Descriptor instead.
func (*ShieldDownload) Descriptor() ([]byte, []int) {
	return file_client_shield_proto_rawDescGZIP(), []int{1}
}

func (x *ShieldDownload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShieldDownload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ShieldConfig is the desired state of shield's watched config directory.
type ShieldConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The complete set of files shield should have. With full_sync = true the client
	// makes the directory EXACTLY match this set: write/replace every listed file and
	// remove any previously-managed file NOT listed, so a removed policy actually
	// disappears from the edge. With full_sync = false it is an upsert (no deletions),
	// for incremental pushes. Writes are atomic (temp + rename) so shield never reads
	// a half-written file.
	Files    []*ShieldFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	FullSync bool          `protobuf:"varint,2,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"`
	// Opaque version/hash of this bundle, surfaced back as shield's
	// active_config_version so the control plane can track what each edge runs.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShieldConfig) Reset() {
	*x = ShieldConfig{}
	mi := &file_client_shield_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldConfig) ProtoMessage() {}

func (x *ShieldConfig) ProtoReflect() protoreflect.Message {
	mi := &file_client_shield_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldConfig.ProtoReflect.Descriptor instead.
func (*ShieldConfig) Descriptor() ([]byte, []int) {
	return file_client_shield_proto_rawDescGZIP(), []int{2}
}

func (x *ShieldConfig) GetFiles() []*ShieldFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ShieldConfig) GetFullSync() bool {
	if x != nil {
		return x.FullSync
	}
	return false
}

func (x *ShieldConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_client_shield_proto protoreflect.FileDescriptor

const file_client_shield_proto_rawDesc = "" +
	"\n" +
	"\x13client/shield.proto\x12\x06client\"\xa6\x01\n" +
	"\n" +
	"ShieldFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\x06inline\x18\x02 \x01(\fH\x00R\x06inline\x124\n" +
	"\bdownload\x18\x03 \x01(\v2\x16.client.ShieldDownloadH\x00R\bdownload\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04modeB\b\n" +
	"\x06source\"<\n" +
	"\x0eShieldDownload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"o\n" +
	"\fShieldConfig\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.client.ShieldFileR\x05files\x12\x1b\n" +
	"\tfull_sync\x18\x02 \x01(\bR\bfullSync\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversionB0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_shield_proto_rawDescOnce sync.Once
	file_client_shield_proto_rawDescData []byte
)

func file_client_shield_proto_rawDescGZIP() []byte {
	file_client_shield_proto_rawDescOnce.Do(func() {
		file_client_shield_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_shield_proto_rawDesc), len(file_client_shield_proto_rawDesc)))
	})
	return file_client_shield_proto_rawDescData
}

var file_client_shield_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_client_shield_proto_goTypes = []any{
	(*ShieldFile)(nil),     // 0: client.ShieldFile
	(*ShieldDownload)(nil), // 1: client.ShieldDownload
	(*ShieldConfig)(nil),   // 2: client.ShieldConfig
}
var file_client_shield_proto_depIdxs = []int32{
	1, // 0: client.ShieldFile.download:type_name -> client.ShieldDownload
	0, // 1: client.ShieldConfig.files:type_name -> client.ShieldFile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_client_shield_proto_init() }
func file_client_shield_proto_init() {
	if File_client_shield_proto != nil {
		return
	}
	file_client_shield_proto_msgTypes[0].OneofWrappers = []any{
		(*ShieldFile_Inline)(nil),
		(*ShieldFile_Download)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_shield_proto_rawDesc), len(file_client_shield_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_shield_proto_goTypes,
		DependencyIndexes: file_client_shield_proto_depIdxs,
		MessageInfos:      file_client_shield_proto_msgTypes,
	}.Build()
	File_client_shield_proto = out.File
	file_client_shield_proto_goTypes = nil
	file_client_shield_proto_depIdxs = nil
}
