// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: client/stats.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPUStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent    float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	LoadAvg_1       float64                `protobuf:"fixed64,2,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5       float64                `protobuf:"fixed64,3,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15      float64                `protobuf:"fixed64,4,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	CoreStats       map[string]float64     `protobuf:"bytes,5,rep,name=core_stats,json=coreStats,proto3" json:"core_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Temperature     float64                `protobuf:"fixed64,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	ProcessCount    int32                  `protobuf:"varint,7,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	ThreadCount     int32                  `protobuf:"varint,8,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	ContextSwitches int64                  `protobuf:"varint,9,opt,name=context_switches,json=contextSwitches,proto3" json:"context_switches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CPUStats) Reset() {
	*x = CPUStats{}
	mi := &file_client_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStats) ProtoMessage() {}

func (x *CPUStats) ProtoReflect() protoreflect.Message {
	mi := &file_client_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStats.ProtoReflect.Descriptor instead.
func (*CPUStats) Descriptor() ([]byte, []int) {
	return file_client_stats_proto_rawDescGZIP(), []int{0}
}

func (x *CPUStats) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CPUStats) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *CPUStats) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *CPUStats) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *CPUStats) GetCoreStats() map[string]float64 {
	if x != nil {
		return x.CoreStats
	}
	return nil
}

func (x *CPUStats) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CPUStats) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *CPUStats) GetThreadCount() int32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *CPUStats) GetContextSwitches() int64 {
	if x != nil {
		return x.ContextSwitches
	}
	return 0
}

type MemoryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	UsagePercent  float64                `protobuf:"fixed64,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	SwapTotal     uint64                 `protobuf:"varint,5,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed      uint64                 `protobuf:"varint,6,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapFree      uint64                 `protobuf:"varint,7,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	Cached        uint64                 `protobuf:"varint,8,opt,name=cached,proto3" json:"cached,omitempty"`
	Buffers       uint64                 `protobuf:"varint,9,opt,name=buffers,proto3" json:"buffers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStats) Reset() {
	*x = MemoryStats{}
	mi := &file_client_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats) ProtoMessage() {}

func (x *MemoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_client_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats.ProtoReflect.Descriptor instead.
func (*MemoryStats) Descriptor() ([]byte, []int) {
	return file_client_stats_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryStats) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryStats) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryStats) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemoryStats) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *MemoryStats) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryStats) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *MemoryStats) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *MemoryStats) GetCached() uint64 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *MemoryStats) GetBuffers() uint64 {
	if x != nil {
		return x.Buffers
	}
	return 0
}

type DiskStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	FsType        string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	Total         uint64                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,6,opt,name=free,proto3" json:"free,omitempty"`
	UsagePercent  float64                `protobuf:"fixed64,7,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	IoReadBytes   uint64                 `protobuf:"varint,8,opt,name=io_read_bytes,json=ioReadBytes,proto3" json:"io_read_bytes,omitempty"`
	IoWriteBytes  uint64                 `protobuf:"varint,9,opt,name=io_write_bytes,json=ioWriteBytes,proto3" json:"io_write_bytes,omitempty"`
	IoReadOps     uint64                 `protobuf:"varint,10,opt,name=io_read_ops,json=ioReadOps,proto3" json:"io_read_ops,omitempty"`
	IoWriteOps    uint64                 `protobuf:"varint,11,opt,name=io_write_ops,json=ioWriteOps,proto3" json:"io_write_ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStats) Reset() {
	*x = DiskStats{}
	mi := &file_client_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStats) ProtoMessage() {}

func (x *DiskStats) ProtoReflect() protoreflect.Message {
	mi := &file_client_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStats.ProtoReflect.Descriptor instead.
func (*DiskStats) Descriptor() ([]byte, []int) {
	return file_client_stats_proto_rawDescGZIP(), []int{2}
}

func (x *DiskStats) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskStats) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskStats) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *DiskStats) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskStats) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskStats) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *DiskStats) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *DiskStats) GetIoReadBytes() uint64 {
	if x != nil {
		return x.IoReadBytes
	}
	return 0
}

func (x *DiskStats) GetIoWriteBytes() uint64 {
	if x != nil {
		return x.IoWriteBytes
	}
	return 0
}

func (x *DiskStats) GetIoReadOps() uint64 {
	if x != nil {
		return x.IoReadOps
	}
	return 0
}

func (x *DiskStats) GetIoWriteOps() uint64 {
	if x != nil {
		return x.IoWriteOps
	}
	return 0
}

type NetworkStats struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Interfaces     map[string]*InterfaceStats `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Connections    int32                      `protobuf:"varint,2,opt,name=connections,proto3" json:"connections,omitempty"`
	TcpConnections int32                      `protobuf:"varint,3,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`
	UdpConnections int32                      `protobuf:"varint,4,opt,name=udp_connections,json=udpConnections,proto3" json:"udp_connections,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_client_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_client_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_client_stats_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkStats) GetInterfaces() map[string]*InterfaceStats {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NetworkStats) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *NetworkStats) GetTcpConnections() int32 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *NetworkStats) GetUdpConnections() int32 {
	if x != nil {
		return x.UdpConnections
	}
	return 0
}

type InterfaceStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BytesReceived   uint64                 `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BytesSent       uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	PacketsReceived uint64                 `protobuf:"varint,3,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsSent     uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	Errors          uint64                 `protobuf:"varint,5,opt,name=errors,proto3" json:"errors,omitempty"`
	Dropped         uint64                 `protobuf:"varint,6,opt,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterfaceStats) Reset() {
	*x = InterfaceStats{}
	mi := &file_client_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStats) ProtoMessage() {}

func (x *InterfaceStats) ProtoReflect() protoreflect.Message {
	mi := &file_client_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStats.ProtoReflect.Descriptor instead.
func (*InterfaceStats) Descriptor() ([]byte, []int) {
	return file_client_stats_proto_rawDescGZIP(), []int{4}
}

func (x *InterfaceStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *InterfaceStats) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *InterfaceStats) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *InterfaceStats) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *InterfaceStats) GetErrors() uint64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *InterfaceStats) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	KernelVersion string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Uptime        float64                `protobuf:"fixed64,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	LastBoot      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_boot,json=lastBoot,proto3" json:"last_boot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_client_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_client_stats_proto_rawDescGZIP(), []int{5}
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetUptime() float64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *SystemInfo) GetLastBoot() *timestamppb.Timestamp {
	if x != nil {
		return x.LastBoot
	}
	return nil
}

var File_client_stats_proto protoreflect.FileDescriptor

const file_client_stats_proto_rawDesc = "" +
	"\n" +
	"\x12client/stats.proto\x12\x06client\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x03\n" +
	"\bCPUStats\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\x02 \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\x03 \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\x04 \x01(\x01R\tloadAvg15\x12>\n" +
	"\n" +
	"core_stats\x18\x05 \x03(\v2\x1f.client.CPUStats.CoreStatsEntryR\tcoreStats\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x01R\vtemperature\x12#\n" +
	"\rprocess_count\x18\a \x01(\x05R\fprocessCount\x12!\n" +
	"\fthread_count\x18\b \x01(\x05R\vthreadCount\x12)\n" +
	"\x10context_switches\x18\t \x01(\x03R\x0fcontextSwitches\x1a<\n" +
	"\x0eCoreStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xfb\x01\n" +
	"\vMemoryStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12#\n" +
	"\rusage_percent\x18\x04 \x01(\x01R\fusagePercent\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x05 \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\x06 \x01(\x04R\bswapUsed\x12\x1b\n" +
	"\tswap_free\x18\a \x01(\x04R\bswapFree\x12\x16\n" +
	"\x06cached\x18\b \x01(\x04R\x06cached\x12\x18\n" +
	"\abuffers\x18\t \x01(\x04R\abuffers\"\xcc\x02\n" +
	"\tDiskStats\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x05 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x06 \x01(\x04R\x04free\x12#\n" +
	"\rusage_percent\x18\a \x01(\x01R\fusagePercent\x12\"\n" +
	"\rio_read_bytes\x18\b \x01(\x04R\vioReadBytes\x12$\n" +
	"\x0eio_write_bytes\x18\t \x01(\x04R\fioWriteBytes\x12\x1e\n" +
	"\vio_read_ops\x18\n" +
	" \x01(\x04R\tioReadOps\x12 \n" +
	"\fio_write_ops\x18\v \x01(\x04R\n" +
	"ioWriteOps\"\x9f\x02\n" +
	"\fNetworkStats\x12D\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2$.client.NetworkStats.InterfacesEntryR\n" +
	"interfaces\x12 \n" +
	"\vconnections\x18\x02 \x01(\x05R\vconnections\x12'\n" +
	"\x0ftcp_connections\x18\x03 \x01(\x05R\x0etcpConnections\x12'\n" +
	"\x0fudp_connections\x18\x04 \x01(\x05R\x0eudpConnections\x1aU\n" +
	"\x0fInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.client.InterfaceStatsR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x0eInterfaceStats\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x04R\rbytesReceived\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12)\n" +
	"\x10packets_received\x18\x03 \x01(\x04R\x0fpacketsReceived\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12\x16\n" +
	"\x06errors\x18\x05 \x01(\x04R\x06errors\x12\x18\n" +
	"\adropped\x18\x06 \x01(\x04R\adropped\"\xb0\x01\n" +
	"\n" +
	"SystemInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x01R\x06uptime\x127\n" +
	"\tlast_boot\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastBootB0Z.github.com/CloudNativeWorks/elchi-proto/clientb\x06proto3"

var (
	file_client_stats_proto_rawDescOnce sync.Once
	file_client_stats_proto_rawDescData []byte
)

func file_client_stats_proto_rawDescGZIP() []byte {
	file_client_stats_proto_rawDescOnce.Do(func() {
		file_client_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_stats_proto_rawDesc), len(file_client_stats_proto_rawDesc)))
	})
	return file_client_stats_proto_rawDescData
}

var file_client_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_client_stats_proto_goTypes = []any{
	(*CPUStats)(nil),              // 0: client.CPUStats
	(*MemoryStats)(nil),           // 1: client.MemoryStats
	(*DiskStats)(nil),             // 2: client.DiskStats
	(*NetworkStats)(nil),          // 3: client.NetworkStats
	(*InterfaceStats)(nil),        // 4: client.InterfaceStats
	(*SystemInfo)(nil),            // 5: client.SystemInfo
	nil,                           // 6: client.CPUStats.CoreStatsEntry
	nil,                           // 7: client.NetworkStats.InterfacesEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_client_stats_proto_depIdxs = []int32{
	6, // 0: client.CPUStats.core_stats:type_name -> client.CPUStats.CoreStatsEntry
	7, // 1: client.NetworkStats.interfaces:type_name -> client.NetworkStats.InterfacesEntry
	8, // 2: client.SystemInfo.last_boot:type_name -> google.protobuf.Timestamp
	4, // 3: client.NetworkStats.InterfacesEntry.value:type_name -> client.InterfaceStats
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_client_stats_proto_init() }
func file_client_stats_proto_init() {
	if File_client_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_stats_proto_rawDesc), len(file_client_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_stats_proto_goTypes,
		DependencyIndexes: file_client_stats_proto_depIdxs,
		MessageInfos:      file_client_stats_proto_msgTypes,
	}.Build()
	File_client_stats_proto = out.File
	file_client_stats_proto_goTypes = nil
	file_client_stats_proto_depIdxs = nil
}
